#!/usr/bin/env python3
"""Contributor-identity seed table — to close the ORCID / attribution gap.

Operates offline on the already-extracted observatory data
(`observatory/site/src/data/contributors.csv`) joined with the canonical
identity map (`scripts/contributors_map.json`). Produces a fill-in table
that makes the attribution gap explicit: who has a confirmed real name, who
has only a placeholder ORCID, and who is entirely unidentified.

The bus-factor finding showed all human contributors lack a registered
ORCID (`reports/bus_factor.md`); this table is the worksheet for fixing
that — one row per commit author, pre-filled where the identity is known.

Outputs
-------
* `reports/contributor_identity.md`                     — fill-in worksheet
* `observatory/site/src/data/contributor_identity.csv`  — machine-readable seed

Usage:  python scripts/contributor_identity.py
"""
import csv, json, os, sys
from collections import defaultdict
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, 'observatory', 'site', 'src', 'data')
CONTRIB = os.path.join(DATA, 'contributors.csv')
CMAP = os.path.join(HERE, 'contributors_map.json')
OUT_MD = os.path.join(ROOT, 'reports', 'contributor_identity.md')
OUT_CSV = os.path.join(DATA, 'contributor_identity.csv')


def is_real_orcid(orcid):
    """A registered ORCID looks like 0000-0000-0000-0000; placeholders don't."""
    o = (orcid or '').strip()
    return bool(o) and not o.upper().startswith('PLACEHOLDER')


def main():
    cmap = json.load(open(CMAP, encoding='utf-8'))

    # commit authors + their footprint
    totals = defaultdict(int)
    repos = defaultdict(set)
    is_bot_type = {}
    with open(CONTRIB, encoding='utf-8') as f:
        for row in csv.DictReader(f):
            login = row['login']
            totals[login] += int(row['contributions'])
            repos[login].add(row['repo'])
            is_bot_type[login] = (row['type'].strip().lower() == 'bot')

    rows = []
    for login, total in totals.items():
        m = cmap.get(login, {})
        bot = bool(m.get('is_bot')) or is_bot_type.get(login, False)
        real_name = (m.get('real_name') or '').strip()
        orcid = (m.get('orcid') or '').strip()
        has_orcid = is_real_orcid(orcid)
        if bot:
            status = 'bot'
        elif not real_name:
            status = 'needs-name-and-orcid'
        elif not has_orcid:
            status = 'needs-orcid'
        else:
            status = 'complete'
        rows.append({
            'login': login,
            'contributions': total,
            'repos': len(repos[login]),
            'role': m.get('role', ''),
            'real_name': real_name,
            'affiliation': (m.get('affiliation') or '').strip(),
            'orcid': orcid if has_orcid else '',
            'status': status,
        })

    rows.sort(key=lambda r: (r['status'] == 'bot', -r['contributions']))

    humans = [r for r in rows if r['status'] != 'bot']
    needs_name = [r for r in humans if r['status'] == 'needs-name-and-orcid']
    needs_orcid = [r for r in humans if r['status'] == 'needs-orcid']
    complete = [r for r in humans if r['status'] == 'complete']

    # ---- CSV ----
    with open(OUT_CSV, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=['login', 'contributions', 'repos',
            'role', 'real_name', 'affiliation', 'orcid', 'status'])
        w.writeheader()
        w.writerows(rows)

    # ---- worksheet ----
    L = []; A = L.append
    A('# Contributor-identity worksheet')
    A('')
    A('_Generated by `scripts/contributor_identity.py` from '
      '`observatory/site/src/data/contributors.csv` + '
      '`scripts/contributors_map.json` (offline, reproducible). One row per '
      'commit author; bots separated out._')
    A('')
    A('Purpose: close the attribution gap the bus-factor finding surfaced — '
      'every human contributor currently lacks a **registered** ORCID '
      '(`reports/bus_factor.md`). Fill the blank `Real name` / `ORCID` cells '
      'below, then update `scripts/contributors_map.json` and re-run. ORCIDs '
      'shown as blank are either missing or still `PLACEHOLDER-*` in the map.')
    A('')
    A('## Status summary')
    A('')
    A('| Status | Contributors |')
    A('|---|---:|')
    A(f'| Confirmed name **and** registered ORCID | {len(complete)} |')
    A(f'| Confirmed name, ORCID still a placeholder | {len(needs_orcid)} |')
    A(f'| No confirmed name (and no ORCID) | {len(needs_name)} |')
    A(f'| Bots (excluded) | {len(rows) - len(humans)} |')
    A('')
    A(f'**Bottom line: 0 of {len(humans)} human contributors have a registered '
      'ORCID.** The core group already has confirmed names; the gap is ORCID '
      'registration for them plus identification of the occasional contributors.')
    A('')
    A('## Worksheet (commit authors, by contribution volume)')
    A('')
    A('Fill `Real name` and `ORCID` where blank. `—` in ORCID means none on '
      'file (or placeholder).')
    A('')
    A('| GitHub login | Contributions | Repos | Role | Real name | Affiliation | ORCID |')
    A('|---|---:|---:|---|---|---|---|')
    for r in humans:
        A(f'| `{r["login"]}` | {r["contributions"]:,} | {r["repos"]} | '
          f'{r["role"] or "—"} | {r["real_name"] or "**?**"} | '
          f'{r["affiliation"] or "—"} | {r["orcid"] or "—"} |')
    A('')
    A('## Priority: confirmed names awaiting ORCID registration')
    A('')
    if needs_orcid:
        A('These contributors are identified — they only need to register (or '
          'supply) an ORCID. Highest-value rows to fix first.')
        A('')
        A('| Real name | GitHub login | Role | Contributions |')
        A('|---|---|---|---:|')
        for r in sorted(needs_orcid, key=lambda x: -x['contributions']):
            A(f'| {r["real_name"]} | `{r["login"]}` | {r["role"] or "—"} | {r["contributions"]:,} |')
    else:
        A('None.')
    A('')
    A('## To identify: commit authors with no confirmed name')
    A('')
    if needs_name:
        A('| GitHub login | Contributions | Repos |')
        A('|---|---:|---:|')
        for r in sorted(needs_name, key=lambda x: -x['contributions']):
            A(f'| `{r["login"]}` | {r["contributions"]:,} | {r["repos"]} |')
    else:
        A('None — every commit author has a confirmed name.')
    A('')
    A('*Object of analysis: GitHub contributor identities — in scope per '
      '`docs/BOUNDARY_RULES.md`. Related: tracking issue #1 invites '
      'contributors to self-identify.*')

    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')

    print(f'wrote {OUT_MD}')
    print(f'wrote {OUT_CSV}')
    print(f'  commit authors: {len(rows)} ({len(humans)} human, {len(rows)-len(humans)} bot)')
    print(f'  complete: {len(complete)}   needs-orcid: {len(needs_orcid)}   '
          f'needs-name: {len(needs_name)}')


if __name__ == '__main__':
    main()
