#!/usr/bin/env python3
"""Capture-recapture estimate of error-prone sites remaining per dictionary (G3).

Operates offline on the committed OBS-T corpus
(`observatory/site/src/data/correction_events_final.csv`). The two OBS-T
layers are treated as two capture occasions over error-prone *sites*:

* occasion 1 = form era (cfr.tsv web submissions, 2014-2019), n1 sites
* occasion 2 = git era (csl-orig commits, 2019-2026), n2 sites
* m = sites captured in BOTH eras

A **site** is (dict, headword) — the dictionary record. We estimate the
population of records harbouring at least one error, N, via the Chapman
estimator, and derive "remaining" = N_hat - S_obs where S_obs = n1 + n2 - m
(distinct sites already caught). This answers, at order-of-magnitude
precision, "how much correction work is left in dictionary X?" - never
before quantified for CDSL.

Estimators
----------
Chapman (bias-corrected Lincoln-Petersen):
    N_hat = (n1+1)(n2+1)/(m+1) - 1
    var   = (n1+1)(n2+1)(n1-m)(n2-m) / ((m+1)^2 (m+2))
    95% CI = N_hat +/- 1.96*sqrt(var)     (reported only when m >= MIN_M)
Chao lower bound (2-occasion incidence form, robustness):
    f1 = n1 + n2 - 2m (sites seen once), f2 = m (seen twice)
    N_chao >= S_obs + f1^2 / (2 f2)

Design caveats (stated in full in the report)
---------------------------------------------
1. The occasions are SEQUENTIAL, not simultaneous: era-1 fixes remove
   errors, so era-2 recapture of a site requires a *different* residual
   error there. Where sites carry few errors this depresses m and inflates
   N_hat (upward bias).
2. Catchability is heterogeneous and positively correlated (both eras
   gravitate to long, high-traffic entries), which biases N_hat DOWNWARD.
   The two violations pull in opposite directions; we report order of
   magnitude, not precision, and the CI is statistical-only.
3. Site key excludes the error component: the form layer is 77% component-
   unattributed, so including the component collapses matches on missing
   data, not on substance (shown in the sensitivity table).

Outputs
-------
* `reports/error_recapture.md`
* `observatory/site/src/data/error_recapture.csv`   (per-dict estimates)

Usage:  python scripts/error_recapture.py
"""
import csv, math, os, re, sys, unicodedata
from collections import defaultdict
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from build_correction_events import hk_to_iast   # noqa: E402

DATA = os.path.join(ROOT, 'observatory', 'site', 'src', 'data')
EVENTS = os.path.join(DATA, 'correction_events_final.csv')
CAMPAIGNS = os.path.join(DATA, 'obs_t_campaigns.csv')
RECORDS = os.path.join(DATA, 'obs_t_dict_records.csv')
LINKAGE = os.path.join(DATA, 'error_recapture_linkage_summary.csv')
OUT_MD = os.path.join(ROOT, 'reports', 'error_recapture.md')
OUT_CSV = os.path.join(DATA, 'error_recapture.csv')
OUT_CORR_CSV = os.path.join(DATA, 'error_recapture_corrector.csv')

MIN_M = 10          # minimum recaptures for a point estimate
MIN_CORRECTOR = 40  # minimum sites for a corrector to serve as a capture occasion

# Fallback <L> record counts (counted 2026-07-03) for the three originally
# estimable dictionaries. The full 40-dictionary table now lives in the committed
# obs_t_dict_records.csv, regenerated by scripts/error_recapture_linkage.py; this
# literal keeps the script runnable if that file is ever absent. The physical
# cap: N cannot exceed the number of records in the dictionary.
RECORD_COUNTS_FALLBACK = {'pw': 170556, 'mw': 286525, 'bur': 19776}

_IAST_RE = re.compile(r'[āīūṛṝḷḹṅñṭḍṇśṣṃḥ]')
_ASCII_ALPHA_RE = re.compile(r'^[A-Za-z]+$')


def site_key(s):
    """The adopted site key: NFC + casefold + edge punctuation, with pure-ASCII
    cells decoded as Harvard-Kyoto (the cfr form's roman convention).

    `scheme_repair` in reports/error_recapture_linkage.md, adopted there as the
    only join that adds recaptures without linking any non-identical pair. Plain
    casefolding alone is NOT safe: it merges `Ayukta` (= āyukta) into `ayukta`,
    two different records."""
    t = s.strip()
    if _ASCII_ALPHA_RE.match(t) and not _IAST_RE.search(t):
        t = hk_to_iast(t)
    t = unicodedata.normalize('NFC', t.strip()).casefold()
    return re.sub(r'\s+', ' ', t.strip('.,;:!?"\'()[]{}*-–—°˚ '))


def load_record_counts():
    if not os.path.exists(RECORDS):
        return dict(RECORD_COUNTS_FALLBACK), False
    out = {}
    with open(RECORDS, encoding='utf-8') as f:
        for r in csv.DictReader(f):
            if r['records']:
                out[r['dict']] = int(r['records'])
    return (out, True) if out else (dict(RECORD_COUNTS_FALLBACK), False)


RECORD_COUNTS, RECORD_COUNTS_FULL = load_record_counts()


def chapman(n1, n2, m):
    n_hat = (n1 + 1) * (n2 + 1) / (m + 1) - 1
    var = ((n1 + 1) * (n2 + 1) * (n1 - m) * (n2 - m)) / (((m + 1) ** 2) * (m + 2))
    se = math.sqrt(var)
    return n_hat, se, max(n1 + n2 - m, n_hat - 1.96 * se), n_hat + 1.96 * se


def chao_lb(n1, n2, m):
    s_obs = n1 + n2 - m
    f1, f2 = n1 + n2 - 2 * m, m
    if f2 == 0:
        return None
    return s_obs + f1 * f1 / (2 * f2)


def collect(rows, with_component=False, exclude=None, raw_key=False):
    """dict -> {'form': set(sites), 'git': set(sites)}."""
    per = defaultdict(lambda: {'form': set(), 'git': set()})
    for r in rows:
        h = r['headword_iast'].strip()
        if not h:
            continue
        if exclude and (r['dict'], r['date'][:10]) in exclude:
            continue
        k = h if raw_key else site_key(h)
        if not k:
            continue
        key = (k, r['error_component']) if with_component else k
        per[r['dict']][r['source_layer']].add(key)
    return per


def corrector_pairs(rows):
    """Within-era corrector-pair recapture: two correctors working the same
    dictionary in the same era are two capture occasions over the same sites.

    Unlike the two-era design this does not violate closure by construction — the
    occasions overlap in time rather than following each other by five years — so
    it cross-checks the sequential-occasions bias the two-era estimate carries.
    Joint attributions (`a/b`, `ejf_etal`) are dropped: they are not one agent.
    Handle pairs within edit distance 1 (`dhaval_ejf` / `dhavel_ejf`) are dropped
    as the same person typed twice."""
    per = defaultdict(lambda: defaultdict(set))
    for r in rows:
        h, c = r['headword_iast'].strip(), (r['corrector'] or '').strip()
        if not h or not c or '/' in c or c.endswith('_etal') or c == 'unknown':
            continue
        k = site_key(h)
        if k:
            per[(r['dict'], r['source_layer'])][c].add(k)

    def near(a, b):
        if abs(len(a) - len(b)) > 1:
            return False
        if len(a) == len(b):
            return sum(1 for x, y in zip(a, b) if x != y) <= 1
        lo, hi = (a, b) if len(a) < len(b) else (b, a)
        return any(hi[:i] + hi[i + 1:] == lo for i in range(len(hi)))

    out = []
    for (d, layer), cs in per.items():
        big = sorted(((c, s) for c, s in cs.items() if len(s) >= MIN_CORRECTOR),
                     key=lambda kv: (-len(kv[1]), kv[0]))
        for i in range(len(big)):
            for j in range(i + 1, len(big)):
                (a, sa), (b, sb) = big[i], big[j]
                if near(a, b):
                    continue
                n1, n2, m = len(sa), len(sb), len(sa & sb)
                if m < MIN_M:
                    continue
                # a handle like `dhaval_ejf` reads as two people's tags joined;
                # whether it is independent of `funderburkjim` is not knowable
                # from the corpus, so the row is flagged rather than guessed at
                comp = [c for c in (a, b)
                        if '_' in c and not c.startswith('form_corrector_')]
                n_hat, se, lo, hi = chapman(n1, n2, m)
                cap = RECORD_COUNTS.get(d)
                capped = cap is not None and n_hat > cap
                if capped:
                    n_hat, hi, lo = cap, min(hi, cap), min(lo, cap)
                out.append({'dict': d, 'era': layer, 'corrector_1': a,
                            'corrector_2': b, 'n1': n1, 'n2': n2, 'm_overlap': m,
                            's_observed': n1 + n2 - m, 'n_hat': round(n_hat),
                            'ci_low': round(lo), 'ci_high': round(hi),
                            'capped': int(capped),
                            'record_count': RECORD_COUNTS.get(d, ''),
                            'independence': ('unverified — composite-looking '
                                             'handle: ' + ', '.join(comp)
                                             if comp else 'distinct handles')})
    out.sort(key=lambda r: (r['dict'], r['era'], -r['m_overlap']))
    return out


def load_linkage():
    """Per-rule verdicts from the committed linkage study, if it has been run.

    Read, never recomputed: the two reports must not be able to disagree about a
    false-match rate. Regenerate with scripts/error_recapture_linkage.py."""
    if not os.path.exists(LINKAGE):
        return {}
    with open(LINKAGE, encoding='utf-8') as f:
        return {r['rule']: r for r in csv.DictReader(f)}


def estimates(per):
    """List of per-dict stat dicts, sorted by S_obs desc."""
    out = []
    for d, s in per.items():
        n1, n2 = len(s['form']), len(s['git'])
        m = len(s['form'] & s['git'])
        s_obs = n1 + n2 - m
        row = {'dict': d, 'n1_form': n1, 'n2_git': n2, 'm_overlap': m,
               's_observed': s_obs, 'estimable': int(m >= MIN_M and n1 > 0 and n2 > 0),
               'n_hat': '', 'ci_low': '', 'ci_high': '', 'chao_hetero': '',
               'record_count': RECORD_COUNTS.get(d, ''), 'capped': '',
               'remaining_hat': ''}
        if row['estimable']:
            n_hat, se, lo, hi = chapman(n1, n2, m)
            cap = RECORD_COUNTS.get(d)
            capped = cap is not None and n_hat > cap
            if capped:
                n_hat, hi = cap, min(hi, cap)
                lo = min(lo, cap)
            row.update(n_hat=round(n_hat), ci_low=round(lo), ci_high=round(hi),
                       capped=int(capped), remaining_hat=round(n_hat - s_obs))
            c = chao_lb(n1, n2, m)
            row['chao_hetero'] = round(min(c, cap) if cap else c) if c is not None else ''
        out.append(row)
    out.sort(key=lambda r: -r['s_observed'])
    return out


def load_campaign_excl():
    """Set of (dict_lower, ISO-date) covered by a documented campaign."""
    excl = set()
    if not os.path.exists(CAMPAIGNS):
        return excl
    with open(CAMPAIGNS, encoding='utf-8') as f:
        for r in csv.DictReader(f):
            for d in r['dicts'].split('|'):
                if d.strip():
                    excl.add((d.strip().lower(), r['date']))
    return excl


def main():
    with open(EVENTS, encoding='utf-8') as f:
        rows = list(csv.DictReader(f))

    # main analysis: site = (dict, headword) under the adopted site key
    per = collect(rows)
    main_est = estimates(per)
    # the previously published key (raw string), kept as a comparison row
    raw_est = estimates(collect(rows, raw_key=True))
    corr_rows = corrector_pairs(rows)
    linkage = load_linkage()
    # sensitivity a: component in the site key
    comp_est = estimates(collect(rows, with_component=True))
    # sensitivity b: exclude events on documented campaign (dict, date) days
    excl = load_campaign_excl()
    n_excl = sum(1 for r in rows if (r['dict'], r['date'][:10]) in excl)
    camp_est = estimates(collect(rows, exclude=excl))

    est_rows = [r for r in main_est if r['estimable']]
    total_obs = sum(r['s_observed'] for r in main_est)
    total_hat = sum(r['n_hat'] for r in est_rows)
    total_rem = sum(r['remaining_hat'] for r in est_rows)
    total_obs_est = sum(r['s_observed'] for r in est_rows)

    with open(OUT_CSV, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(main_est[0].keys()))
        w.writeheader()
        for r in main_est:
            w.writerow(r)

    if corr_rows:
        with open(OUT_CORR_CSV, 'w', encoding='utf-8', newline='') as f:
            w = csv.DictWriter(f, fieldnames=list(corr_rows[0].keys()))
            w.writeheader()
            for r in corr_rows:
                w.writerow(r)

    by = {r['dict']: r for r in main_est}
    raw_by = {r['dict']: r for r in raw_est}
    camp_by = {r['dict']: r for r in camp_est}
    comp_by = {r['dict']: r for r in comp_est}

    L = []; A = L.append
    A('# Capture-recapture: how much correction work is left?')
    A('')
    A('_Generated by `scripts/error_recapture.py` from `observatory/site/src/data/'
      'correction_events_final.csv` (offline, reproducible). Roadmap: Workstream '
      'G3. Estimand: dictionary records ("sites") harbouring at least one error, '
      'per dictionary — an order-of-magnitude estimate, not a precision one._')
    A('')
    A('## Design')
    A('')
    A('OBS-T\'s two correction layers act as two capture occasions over error-'
      'prone sites (dict + headword): the **form era** (cfr.tsv web submissions, '
      '2014-2019) and the **git era** (csl-orig commits, 2019-2026). Sites '
      'corrected in both eras are "recaptures"; the Chapman estimator converts '
      'capture/recapture counts into an estimate of the total error-site '
      f'population N. Point estimates only where recaptures m >= {MIN_M}.')
    A('')
    A('**Site key.** Sites are matched on the headword after a scheme repair: '
      'NFC + casefold + edge punctuation, with pure-ASCII cells decoded as '
      'Harvard-Kyoto, which is what the cfr form used for roman cells. Six '
      'candidate joins (including diacritic folding, edit distance 1, and the '
      '`<L>` record number) were scored for false matches against csl-orig '
      'itself; this is the only one that adds recaptures without linking a '
      'single non-identical pair. See `reports/error_recapture_linkage.md` — the '
      'looser joins are rejected there with measured rates, not with an opinion.')
    A('')
    A('**Assumption violations, stated plainly.** (1) The occasions are '
      'sequential: a site fixed completely in era 1 cannot be recaptured in era '
      '2, which depresses m and biases N upward. (2) Catchability is '
      'heterogeneous and positively correlated across eras (both target long, '
      'high-traffic entries), biasing N downward. The violations pull in '
      'opposite directions; confidence intervals are statistical-only and do '
      'not cover these design biases. (3) Population closure is imperfect '
      '(new errors can be introduced between eras), a second upward pressure. '
      'Read every figure as order-of-magnitude.')
    A('')
    A('## Headline')
    A('')
    A('| Metric | Value |')
    A('|---|---:|')
    A(f'| Correction events analysed | {len(rows):,} |')
    A(f'| Distinct error sites observed (all 43 dicts) | {total_obs:,} |')
    A(f'| Dictionaries with enough overlap to estimate (m >= {MIN_M}) | {len(est_rows)} |')
    A(f'| Estimated error-site population (those dicts) | **~{total_hat:,}** |')
    A(f'| Sites already corrected there | {total_obs_est:,} |')
    A(f'| **Estimated error sites still uncorrected there** | **~{total_rem:,}** |')
    A('')
    A('## Per-dictionary estimates')
    A('')
    A('| Dict | Records | Form sites n1 | Git sites n2 | Recaptures m | Observed | N (Chapman) | 95% CI | Chao (heterogeneity scenario) | Remaining |')
    A('|---|---:|---:|---:|---:|---:|---:|---|---:|---:|')
    for r in est_rows:
        n_show = f"~{r['n_hat']:,}" + (' (capped)' if r['capped'] else '')
        A(f"| **{r['dict']}** | {r['record_count']:,} | {r['n1_form']:,} | {r['n2_git']:,} | {r['m_overlap']} "
          f"| {r['s_observed']:,} | {n_show} | {r['ci_low']:,}-{r['ci_high']:,} "
          f"| {r['chao_hetero']:,} | **~{r['remaining_hat']:,}** |")
    A('')
    A('Estimates are capped at the dictionary\'s physical record count. Those '
      + (f'counts now cover all {len(RECORD_COUNTS)} dictionaries with a '
         '`csl-orig` v02 source (`obs_t_dict_records.csv`, regenerated by '
         '`scripts/error_recapture_linkage.py`), so a newly estimable dictionary '
         'no longer arrives without a denominator.'
         if RECORD_COUNTS_FULL else
         'counts are the three literals embedded in this script — run '
         '`scripts/error_recapture_linkage.py` to derive the full table.')
      + ' A raw estimate that EXCEEDS the cap (bur) signals that headword-match '
        'noise between the two eras is inflating the estimate there — read a '
        'capped row as "the whole dictionary should be treated as unproofread", '
        'not as a precise count.')
    A('')
    A('Dictionaries below the overlap threshold (lower bound = observed sites only):')
    A('')
    A('| Dict | n1 | n2 | m | Observed (lower bound on N) |')
    A('|---|---:|---:|---:|---:|')
    for r in main_est:
        if not r['estimable']:
            A(f"| {r['dict']} | {r['n1_form']:,} | {r['n2_git']:,} | {r['m_overlap']} | {r['s_observed']:,} |")
    A('')
    A('## Sensitivity')
    A('')
    A('**(a) Site key with the error component.** Including `error_component` in '
      'the site key collapses recaptures (e.g. '
      f"mw m {by['mw']['m_overlap']} -> {comp_by['mw']['m_overlap']}, "
      f"pw m {by['pw']['m_overlap']} -> {comp_by['pw']['m_overlap']}) — but this "
      'reflects missing data, not substance: 77% of form-era events are '
      'component-unattributed (`evidence_level = inferred`), so component keys '
      'mismatch mechanically. The headword-level key is the honest unit.')
    A('')
    A(f'**(b) Campaign exclusion.** Dropping the {n_excl:,} events that fall on '
      'documented campaign days for their dictionary (obs_t_campaigns.csv) '
      'moves the estimable dictionaries to:')
    A('')
    A('| Dict | N (all events) | N (campaigns excluded) |')
    A('|---|---:|---:|')
    for r in est_rows:
        c = camp_by.get(r['dict'], {})
        cn = f"~{c.get('n_hat'):,}" if c.get('estimable') else 'below threshold'
        A(f"| {r['dict']} | ~{r['n_hat']:,} | {cn} |")
    A('')
    A('**(c) Heterogeneous catchability.** Chapman assumes every site is equally '
      'catchable; in reality correctors specialise, so the two eras oversample '
      'the same prominent entries and Chapman UNDERESTIMATES. The Chao column '
      'is the standard estimate under that heterogeneity scenario (Chao 1987): '
      'read Chapman and Chao as the two ends of the plausible range, not as '
      'point-and-floor. Both are capped at the record count; for pw and mw the '
      'heterogeneity scenario saturates near the whole dictionary — consistent '
      'with OCR-derived text where most long entries harbour at least one '
      'defect.')
    A('')
    A('**(d) Site key / record linkage.** The join between the two eras was '
      'previously the raw headword string. It is now the scheme-repaired key '
      'described under Design, which moves the estimable dictionaries to:')
    A('')
    A('| Dict | m (raw key) | m (adopted key) | N (raw key) | N (adopted key) |')
    A('|---|---:|---:|---:|---:|')
    for r in est_rows:
        o = raw_by.get(r['dict'], {})
        on = f"~{o['n_hat']:,}" if o.get('estimable') else 'below threshold'
        A(f"| {r['dict']} | {o.get('m_overlap', '—')} | {r['m_overlap']} | {on} "
          f"| ~{r['n_hat']:,} |")
    A('')
    if linkage:
        A('Looser joins were tested and **rejected on measured evidence**, not '
          'left untried — diacritic folding, edit distance 1, and the `<L>` '
          'record number each raise m substantially and each manufactures false '
          'recaptures, which would shrink the "work remaining" headline by '
          'artefact. Because N is inversely proportional to m, a permissive join '
          'is not a neutral choice:')
        A('')
        A('| Join | Total m | Measured false-match rate | Basis of that rate | Dictionaries estimable |')
        A('|---|---:|---:|---|---:|')
        shown = {'exact': 'raw headword (previous)',
                 'scheme_repair': 'scheme-repaired headword (adopted)',
                 'fold': 'diacritic folding',
                 'fold_ed1': 'folding + edit distance 1',
                 'lcode': 'csl-orig `<L>` number'}
        for rule, label in shown.items():
            a = linkage.get(rule)
            if not a:
                continue
            rate = (f"{float(a['false_match_rate']):.0%}"
                    if a['false_match_rate'] else 'links no non-identical pair')
            A(f"| {label} | {int(a['total_m']):,} | {rate} | {a['basis']} | "
              f"{a['dicts_estimable']} |")
        A('')
        A('Full method and per-dictionary scoring: '
          '`reports/error_recapture_linkage.md`.')
        A('')
    if corr_rows:
        A('## Corrector-pair recapture (within-era cross-check)')
        A('')
        A('The two-era design has one violation it cannot escape: the occasions '
          'are five years apart, so a site fixed completely in era 1 cannot be '
          'recaptured in era 2, which depresses m and inflates N. Treating two '
          '**correctors working the same dictionary in the same era** as the two '
          'occasions removes that violation — they sample concurrently — at the '
          'cost of a different one: correctors specialise, so their catchability '
          'is heterogeneous and positively correlated, which biases the estimate '
          'DOWN. A corrector-pair estimate below the two-era estimate for the '
          'same dictionary is therefore the expected pattern, and the size of the '
          'gap is informative about how much of the two-era figure is the '
          'sequential-occasions artefact.')
        A('')
        A('| Dict | Era | Corrector 1 | Corrector 2 | n1 | n2 | m | N (Chapman) | 95% CI | Two-era N | Occasions independent? |')
        A('|---|---|---|---|---:|---:|---:|---:|---|---:|---|')
        for r in corr_rows:
            two = by.get(r['dict'], {})
            tn = f"~{two['n_hat']:,}" if two.get('estimable') else '—'
            ind = 'yes, distinct handles' if r['independence'] == 'distinct handles' \
                else '⚠ ' + r['independence'].split(': ', 1)[-1] + ' reads as a joint tag'
            A(f"| {r['dict']} | {r['era']} | `{r['corrector_1']}` | "
              f"`{r['corrector_2']}` | {r['n1']:,} | {r['n2']:,} | {r['m_overlap']} "
              f"| ~{r['n_hat']:,}{' (capped)' if r['capped'] else ''} "
              f"| {r['ci_low']:,}-{r['ci_high']:,} | {tn} | {ind} |")
        A('')
        spread = defaultdict(list)
        for r in corr_rows:
            spread[(r['dict'], r['era'])].append(r['n_hat'])
        wide = sorted(((max(v) / min(v), k, min(v), max(v))
                       for k, v in spread.items() if len(v) > 1 and min(v)),
                      reverse=True)
        new_dicts = sorted({r['dict'] for r in corr_rows} - {r['dict'] for r in est_rows})
        if new_dicts:
            one = len(new_dicts) == 1
            A(f'- **{"A dictionary" if one else "Dictionaries"} the two-era '
              f'design cannot reach but this one can: {", ".join(new_dicts)}.** '
              f'{"Its" if one else "Their"} two-era overlap is below threshold, '
              'yet a single era holds two correctors with enough shared sites to '
              'estimate from — so the "not estimable" verdict on a dictionary is '
              'a property of the two-era design, not always of the evidence.')
        if wide:
            ratio, (d, era), lo, hi = wide[0]
            A(f'- **The spread across corrector pairs is the heterogeneity, '
              f'measured.** In {d} ({era} era) the estimate ranges ~{lo:,} to '
              f'~{hi:,} depending on which two correctors are treated as the '
              f'occasions — a factor of {ratio:.1f}. Sensitivity (c) argues from '
              'theory that catchability is heterogeneous; this is that '
              'heterogeneity as a number, and it bounds how much precision any '
              'single Chapman figure in this report can carry.')
        A('- Joint attributions (`a/b`, `_etal`) and handle pairs one keystroke '
          'apart are excluded: neither is two independent observers. What remains '
          'still assumes a corrector\'s handle is one person and that two '
          'correctors chose their entries independently — the second assumption '
          'is certainly false in a coordinated campaign, which is why this is a '
          'cross-check on the order of magnitude rather than a replacement '
          'estimate.')
        A('')
    A('## Reading')
    A('')
    if est_rows:
        top = est_rows[0]
        A(f'- The two eras overlap remarkably little: of {total_obs:,} observed '
          'error sites org-wide, only a few hundred were touched in both eras. '
          'Under mark-recapture logic, low overlap between two substantial '
          'samples means the underlying population is LARGE: what has been '
          'corrected so far is a minority of what exists.')
        for r in est_rows:
            pct = 100 * r['s_observed'] / r['n_hat']
            share = 100 * r['n_hat'] / r['record_count'] if r['record_count'] else None
            cap_note = ' (estimate capped at the full dictionary)' if r['capped'] else ''
            A(f"- **{r['dict']}**: ~{r['n_hat']:,} error-prone records estimated"
              f"{cap_note} = ~{share:.0f}% of its {r['record_count']:,} records; "
              f"{r['s_observed']:,} corrected so far = **~{pct:.0f}% of the "
              f"estimated work done**, ~{r['remaining_hat']:,} records still "
              'awaiting a first correction (Chapman scenario; under '
              'heterogeneity the remaining share is larger).')
        A('- Most dictionaries cannot be estimated yet — their two-era overlap '
          'is below threshold. That is itself a finding: correction effort has '
          'been so concentrated (and era-partitioned) that for most dictionaries '
          'we cannot even bound the remaining work from correction history alone.')
    A('')
    A('*Object of analysis: correction events over source text (per '
      '`docs/BOUNDARY_RULES.md`). Method: Chapman 1951; Chao 1987 heterogeneity scenario. '
      'Candidate paper track — see `Uprava/ARTICLES.md`.*')

    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')

    print(f'wrote {OUT_MD}')
    print(f'wrote {OUT_CSV}')
    if corr_rows:
        print(f'wrote {OUT_CORR_CSV}  ({len(corr_rows)} corrector pairs)')
    print(f'  estimable dicts: {[r["dict"] for r in est_rows]}')
    print(f'  total N_hat (estimable): {total_hat:,}  remaining: {total_rem:,}')
    print(f'  campaign-excluded events: {n_excl:,}')


if __name__ == '__main__':
    main()
