#!/usr/bin/env python3
"""OBS-T Phase 7h/8 — robustness / sensitivity for the two-axis hypotheses.

Shows the headlines survive resampling and the removal of the dominant dictionary
or a whole layer, on the existing table (no re-mining):

* **H2** location × dictionary Cramer's V — commit-block bootstrap CI, minus-PW,
  git-only.
* **H1** micro-edit rate (a small surface edit) — overall, per layer, with Wilson
  CIs, plus the location mix on derived labels.

Input : observatory/site/src/data/correction_events_final.csv
Output: reports/obs_t_robustness.md, observatory/site/src/data/obs_t_robustness.json

Usage:  python scripts/obs_t_robustness.py
"""
import csv, json, os, random, sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, 'observatory', 'site', 'src', 'data')
IN_CSV = os.path.join(DATA, 'correction_events_final.csv')
OUT_MD = os.path.join(ROOT, 'reports', 'obs_t_robustness.md')
OUT_JSON = os.path.join(DATA, 'obs_t_robustness.json')
csv.field_size_limit(10_000_000)

sys.path.insert(0, HERE)
from obs_t_rigor import chi2_independence, wilson, MINOR_TYPES  # noqa

B = 300


def is_minor(r):
    try:
        d = int(r['edit_distance'])
    except (ValueError, KeyError):
        d = 9
    return r['edit_type'] in MINOR_TYPES and d <= 3


def v_of(rows, top_dicts):
    table = Counter((r['dict'], r['error_component']) for r in rows
                    if r['dict'] in top_dicts)
    return chi2_independence(table)


def bootstrap_v(sub, top_dicts):
    groups = defaultdict(list)
    for r in sub:
        if r['dict'] in top_dicts:
            groups[r.get('commit_sha') or r.get('event_id')].append(r)
    keys = list(groups)
    if not keys:
        return 0.0, 0.0
    rng = random.Random(0); vs = []
    for _ in range(B):
        table = Counter()
        for _ in range(len(keys)):
            for r in groups[rng.choice(keys)]:
                table[(r['dict'], r['error_component'])] += 1
        vs.append(chi2_independence(table)[3])
    vs.sort()
    return round(vs[int(0.025 * B)], 3), round(vs[int(0.975 * B)], 3)


def minor_rate(rows):
    k = sum(1 for r in rows if is_minor(r))
    p, lo, hi = wilson(k, len(rows))
    return round(p, 4), round(lo, 4), round(hi, 4), len(rows)


def main():
    with open(IN_CSV, encoding='utf-8') as f:
        rows = list(csv.DictReader(f))
    derived = [r for r in rows if r['evidence_level'] == 'derived']

    # H2 on LOCATION (derived only)
    top_dicts = [d for d, _ in Counter(r['dict'] for r in derived).most_common(15)]
    sub = [r for r in derived if r['dict'] in top_dicts]
    base = v_of(derived, top_dicts)
    boot = bootstrap_v(sub, top_dicts)
    no_pw = [d for d in top_dicts if d != 'pw']
    nopw = v_of([r for r in derived if r['dict'] != 'pw'], no_pw)
    git = [r for r in derived if r['source_layer'] == 'git']
    git_top = [d for d, _ in Counter(r['dict'] for r in git).most_common(15)]
    gitv = v_of(git, git_top)

    # H1 micro-edit rate
    h1_all = minor_rate(rows)
    h1_form = minor_rate([r for r in rows if r['source_layer'] == 'form'])
    h1_git = minor_rate([r for r in rows if r['source_layer'] == 'git'])
    loc_mix = Counter(r['error_component'] for r in derived)
    tl = sum(loc_mix.values())

    out = {
        'generatedAt': datetime.now(timezone.utc).isoformat(),
        'h2_location': {
            'base': {'cramers_v': base[3], 'p': base[2]},
            'bootstrap_v_ci95': list(boot),
            'minus_pw': base[3] and nopw[3], 'minus_pw_v': nopw[3],
            'git_only_v': gitv[3],
        },
        'h1_minor_edit': {'all': h1_all, 'form': h1_form, 'git': h1_git},
        'location_mix_derived': {k: round(v / tl, 4) for k, v in loc_mix.most_common()},
    }
    with open(OUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    L = []; A = L.append
    A('# Robustness & sensitivity — two-axis (OBS-T)')
    A('')
    A('_Generated by `scripts/obs_t_robustness.py`._')
    A('')
    A('## H2 — location × dictionary effect is robust (derived labels)')
    A('')
    A('| variant | Cramér\'s V | note |')
    A('|---|---:|---|')
    A(f'| all top-15 dicts | {base[3]} | p {"<0.001" if base[2] < 0.001 else base[2]} |')
    A(f'| commit-block bootstrap 95% CI | [{boot[0]}, {boot[1]}] | resampled commit/event blocks (B={B}) |')
    A(f'| minus PW | {nopw[3]} | effect persists |')
    A(f'| git layer only | {gitv[3]} | positional labels only |')
    A('')
    A('## H1 — micro-edit rate by layer')
    A('')
    A('Minor-edit rate = a small surface edit (edit_type spelling/diacritic/case/'
      'spacing/punctuation/digit and edit distance <= 3). Raw source/markup edits '
      'are retained in the table but are not counted as Sanskrit micro-edits.')
    A('')
    A('| subset | minor-edit rate (95% CI) | n |')
    A('|---|---|---:|')
    for name, d in (('all', h1_all), ('form', h1_form), ('git', h1_git)):
        A(f'| {name} | {d[0]:.1%} [{d[1]:.1%}, {d[2]:.1%}] | {d[3]:,} |')
    A('')
    A('## Location mix (derived) — the clean microstructure typology')
    A('')
    A('| location | share |')
    A('|---|---:|')
    for c, v in loc_mix.most_common():
        A(f'| {c} | {v/tl:.1%} |')
    A('')
    A('*Object of analysis in scope per `docs/BOUNDARY_RULES.md`.*')
    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')

    print(f'wrote {OUT_MD}')
    print(f'wrote {OUT_JSON}')
    print(f'  H2 V base={base[3]} boot95=[{boot[0]},{boot[1]}] minusPW={nopw[3]} gitOnly={gitv[3]}')
    print(f'  H1 minor-edit all={h1_all[0]:.1%} form={h1_form[0]:.1%} git={h1_git[0]:.1%}')
    print(f'  location mix derived: {loc_mix.most_common()}')


if __name__ == '__main__':
    main()
