#!/usr/bin/env python3
"""OBS-T Phase 7f — correction campaigns from the hand log (history.txt).

Parses `../CORRECTIONS/history.txt` (the maintainers' dated change log) into
structured campaigns — date, magnitude, dictionaries, and category — so the
diachronic story can distinguish **discrete bulk campaigns** (one-off IAST
conversions, AS-number passes) from **organic** correction-form trickle. This
hardens H3: an apparent trend (e.g. encoding/orthography falling) is partly the
signature of conversion campaigns completing, not only gradual drift.

Input : ../CORRECTIONS/history.txt
Outputs: observatory/site/src/data/obs_t_campaigns.csv
         reports/obs_t_campaigns.md

Usage:  python scripts/obs_t_campaigns.py
"""
import csv, os, re, sys
from collections import Counter, defaultdict
from datetime import datetime
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GH_ROOT = os.path.dirname(ROOT)
HIST = os.path.join(GH_ROOT, 'CORRECTIONS', 'history.txt')
DATA = os.path.join(ROOT, 'observatory', 'site', 'src', 'data')
OUT_CSV = os.path.join(DATA, 'obs_t_campaigns.csv')
OUT_MD = os.path.join(ROOT, 'reports', 'obs_t_campaigns.md')

DICT_CODES = {
    'ACC', 'AE', 'AP', 'AP90', 'APES', 'BEN', 'BHS', 'BOP', 'BOR', 'BUR', 'CAE',
    'CCS', 'GRA', 'GST', 'IEG', 'INM', 'KRM', 'MCI', 'MD', 'MW', 'MW72', 'MWE',
    'PD', 'PE', 'PGN', 'PUI', 'PW', 'PWG', 'PWK', 'SCH', 'SHS', 'SKD', 'SNP',
    'STC', 'VCP', 'VEI', 'WIL', 'YAT', 'PWG2013',
}
_DATE = re.compile(
    r'^([A-Z][a-z]{2,8})\.?\s+(\d{1,2}),?\s+(\d{4})\b', re.M)
_MAG = [re.compile(p, re.I) for p in (
    r'roughly\s+(\d{2,5})', r'about\s+(\d{2,5})', r'~\s*(\d{2,5})',
    r'\(\s*~?\s*(\d{2,5})\s*\)', r'\((\d{3,5})\)')]

CATEGORY = [
    ('citation-source', r'literary source|source abbreviation|source change|'
                        r'abbreviation|biblio'),
    ('iast-encoding', r'iast|c-cedilla|cedilla|diacritic|unicode|\butf\b|'
                      r'meta-line conversion|conversion of'),
    ('as-numbers', r'\bas\b.*(number|letter)|letter-number|as number'),
    ('links', r'link|rvlink|rgveda|reference.*display'),
    ('hyphen-markup', r"missing '-'|hyphen|markup|sanhw|revise"),
    ('page-proofing', r'page|editing of|finishes'),
    ('correction-form', r'correction form'),
]


def parse_date(mon, day, year):
    for fmt in ('%b %d %Y', '%B %d %Y'):
        try:
            return datetime.strptime(f'{mon[:3] if fmt.startswith("%b") else mon} {day} {year}', fmt)
        except ValueError:
            continue
    return None


def categorize(text):
    t = text.lower()
    for label, pat in CATEGORY:
        if re.search(pat, t):
            return label
    return 'other'


def parse():
    text = open(HIST, encoding='utf-8', errors='replace').read()
    marks = list(_DATE.finditer(text))
    out = []
    for i, m in enumerate(marks):
        start = m.start()
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        block = text[start:end]
        dt = parse_date(m.group(1), m.group(2), m.group(3))
        if not dt:
            continue
        desc = ' '.join(block.split())
        mag = 0
        for rx in _MAG:
            mm = rx.search(block)
            if mm:
                mag = int(mm.group(1)); break
        dicts = sorted({w for w in re.findall(r'\b[A-Z][A-Z0-9]{1,6}\b', block)
                        if w in DICT_CODES})
        out.append({'date': dt.date().isoformat(), 'year': dt.year,
                    'magnitude': mag, 'category': categorize(block),
                    'dicts': '|'.join(dicts),
                    'desc': desc[:200]})
    return out


def main():
    camps = parse()
    camps.sort(key=lambda c: c['date'])
    with open(OUT_CSV, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=['date', 'year', 'magnitude', 'category',
                                          'dicts', 'desc'])
        w.writeheader(); w.writerows(camps)

    n = len(camps)
    documented = sum(c['magnitude'] for c in camps)
    by_cat = Counter()
    cat_mag = defaultdict(int)
    by_year_mag = defaultdict(int)
    for c in camps:
        by_cat[c['category']] += 1
        cat_mag[c['category']] += c['magnitude']
        by_year_mag[c['year']] += c['magnitude']
    biggest = sorted(camps, key=lambda c: -c['magnitude'])[:10]

    L = []; A = L.append
    A('# Correction campaigns from the hand log (OBS-T)')
    A('')
    A(f'_Generated by `scripts/obs_t_campaigns.py` from `../CORRECTIONS/history.txt`. '
      f'{n} dated log entries, {documented:,} corrections with a stated magnitude._')
    A('')
    A('> **Why this matters (H3).** The diachronic component trends are not purely '
      'organic: a sizeable share of early correction volume comes from **discrete '
      'bulk campaigns** — one-off IAST/meta-line conversions and AS-number passes — '
      'that ran and finished. A "falling encoding/orthography" trend is partly the '
      'signature of those conversions completing, not only gradual drift. This '
      'separates campaign-driven from organic change.')
    A('')
    A('## Documented campaign volume by category')
    A('')
    A('| category | campaigns | stated corrections |')
    A('|---|---:|---:|')
    for cat, cnt in by_cat.most_common():
        A(f'| {cat} | {cnt} | {cat_mag[cat]:,} |')
    A('')
    A('## Stated volume by year')
    A('')
    A('| year | documented corrections |')
    A('|---|---:|')
    for y in sorted(by_year_mag):
        A(f'| {y} | {by_year_mag[y]:,} |')
    A('')
    A('## Ten largest campaigns')
    A('')
    A('| date | mag | category | dicts | description |')
    A('|---|---:|---|---|---|')
    for c in biggest:
        A(f'| {c["date"]} | {c["magnitude"]:,} | {c["category"]} | {c["dicts"]} '
          f'| {c["desc"][:80]} |')
    A('')
    A('*Magnitudes are the maintainers\' stated approximations ("~", "about", '
      '"roughly"); read as orders of magnitude. Object of analysis in scope per '
      '`docs/BOUNDARY_RULES.md`.*')
    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')

    print(f'wrote {OUT_CSV}  ({n} campaigns)')
    print(f'wrote {OUT_MD}')
    print(f'  documented corrections: {documented:,}')
    print(f'  by category: {by_cat.most_common()}')
    print(f'  largest: {biggest[0]["date"]} {biggest[0]["magnitude"]} {biggest[0]["category"]}')


if __name__ == '__main__':
    main()
