#!/usr/bin/env python3
"""OBS-T Phase 7i — machine silver-validation of the old fallback labels.

No human gold exists yet, but we can still audit the empirical-cluster fallback
that used to populate failed form joins: on form events where the csl-orig
**headword join succeeded** (evidence=derived, the more reliable signal), check
how often that fallback would have produced the *same* component. Low agreement
is the reason release rows now keep failed joins as `unattributed` instead of
guessing a location. This is a silver diagnostic, not a substitute for the human
gold sample.

Input : observatory/site/src/data/correction_events_final.csv
Output: reports/obs_t_silver.md, observatory/site/src/data/obs_t_silver.json

Usage:  python scripts/obs_t_silver.py
"""
import csv, json, os, sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, 'observatory', 'site', 'src', 'data')
IN_CSV = os.path.join(DATA, 'correction_events_final.csv')
OUT_MD = os.path.join(ROOT, 'reports', 'obs_t_silver.md')
OUT_JSON = os.path.join(DATA, 'obs_t_silver.json')
csv.field_size_limit(10_000_000)

sys.path.insert(0, HERE)
from attribute_components import CLUSTER2COMP  # noqa


def main():
    with open(IN_CSV, encoding='utf-8') as f:
        rows = list(csv.DictReader(f))

    # silver truth = form events where the headword join succeeded (derived)
    overlap = [r for r in rows if r['source_layer'] == 'form'
               and r['evidence_level'] == 'derived']
    n = agree = 0
    per_cluster = defaultdict(lambda: [0, 0])   # cluster -> [agree, total]
    confusion = Counter()
    for r in overlap:
        heur = CLUSTER2COMP.get(r['error_type_empirical'], 'unknown')
        if heur == 'unknown':
            continue                            # heuristic abstains; not a test
        truth = r['error_component']
        n += 1
        ok = heur == truth
        agree += ok
        per_cluster[r['error_type_empirical']][0] += ok
        per_cluster[r['error_type_empirical']][1] += 1
        if not ok:
            confusion[(heur, truth)] += 1

    # how much of the corpus is now the inferred/unattributed bucket, and its cluster mix
    inferred = [r for r in rows if r['evidence_level'] == 'inferred']
    inf_clusters = Counter(r['error_type_empirical'] for r in inferred)

    cluster_acc = {c: {'agree': a, 'n': t, 'rate': round(a / t, 3)}
                   for c, (a, t) in sorted(per_cluster.items(), key=lambda kv: -kv[1][1])}
    out = {
        'generatedAt': datetime.now(timezone.utc).isoformat(),
        'silver_truth': 'form events with a successful csl-orig headword join (derived)',
        'testable_overlap': n,
        'heuristic_agreement': round(agree / n, 3) if n else 0,
        'per_cluster': cluster_acc,
        'inferred_total': len(inferred),
        'inferred_cluster_mix': inf_clusters.most_common(),
        'top_disagreements': [{'heuristic': h, 'silver': t, 'n': c}
                              for (h, t), c in confusion.most_common(10)],
    }
    with open(OUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    L = []; A = L.append
    A('# Silver validation of the old fallback labels (OBS-T)')
    A('')
    A('_Generated by `scripts/obs_t_silver.py`. A human-free reliability bound for '
      'the old empirical-cluster fallback: on form events where the csl-orig '
      'headword join succeeded (the more reliable signal), how often would the '
      'fallback heuristic have given the same component? The released table now '
      'keeps failed joins as `unattributed`; this report explains why._')
    A('')
    A('| metric | value |')
    A('|---|---:|')
    A(f'| testable overlap (join-derived form events, heuristic non-abstaining) | {n:,} |')
    A(f'| **heuristic agreement with the join** | **{out["heuristic_agreement"]:.1%}** |')
    A(f'| inferred/unattributed rows in the corpus | {len(inferred):,} |')
    A('')
    A(f'Where the two signals overlap they agree only '
      f'**{out["heuristic_agreement"]:.1%}** of the time — and that near-zero number '
      'is a structural finding, not noise. The join assigns the component by '
      '**location** (a headword typo → `headword`), while the empirical heuristic '
      'assigns it by **edit type** (`typo` → `orthography`). They disagree because '
      'they measure **different axes**. The consequence: the inferred fallback was '
      'filing *type*-axis values (`orthography`, `encoding`) into the *location*-axis '
      'component column. On the trustworthy derived (location) labels the typology '
      'is led by **sense, headword, markup, citation** — not orthography, which is '
      'almost entirely a fallback artifact. **Release policy:** derive the '
      'microstructure (location) typology from derived labels only; keep edit-type '
      '(orthography/encoding/diacritic) in the ERRANT/OCR crosswalk where it belongs; '
      'label join-failures `unattributed` rather than guessing a component.')
    A('')
    A('## Agreement by empirical cluster')
    A('')
    A('| cluster | agreement | n |')
    A('|---|---:|---:|')
    for c, d in cluster_acc.items():
        A(f'| {c} | {d["rate"]:.1%} | {d["n"]:,} |')
    A('')
    A('## What the inferred/unattributed rows look like (cluster mix)')
    A('')
    A('| cluster | inferred/unattributed events |')
    A('|---|---:|')
    for c, k in inf_clusters.most_common():
        A(f'| {c} | {k:,} |')
    A('')
    if out['top_disagreements']:
        A('## Top heuristic→silver disagreements')
        A('')
        A('| heuristic said | join said | n |')
        A('|---|---|---:|')
        for d in out['top_disagreements']:
            A(f'| {d["heuristic"]} | {d["silver"]} | {d["n"]} |')
        A('')
    A('*Silver standard; the human gold sample (`validation/gold_sample.csv`) '
      'remains the definitive check. In scope per `docs/BOUNDARY_RULES.md`.*')
    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')

    print(f'wrote {OUT_MD}')
    print(f'wrote {OUT_JSON}')
    print(f'  testable overlap {n}  heuristic agreement {out["heuristic_agreement"]:.1%}')
    print(f'  per-cluster: {[(c, d["rate"]) for c, d in cluster_acc.items()]}')


if __name__ == '__main__':
    main()
