#!/usr/bin/env python3
"""OBS-T Phase 7e — issue-label cross-corroboration.

A coarse, independent check: the sanskrit-lexicon GitHub issue **type** labels are
a separate human categorization of correction work (a workflow taxonomy:
text-correction / markup / encoding / link-target / content-enhancement /
scan-quality / ...). They do not map 1:1 to the microstructure components and
operate at the issue (not event) level, so this is corroboration, not strict
validation. The question it answers: does the independent issue-typing agree that
correction work is dominated by **text/surface** repair rather than content
enhancement?

Input : observatory/site/src/data/issues.csv  (committed, offline)
Output: reports/obs_t_issuelabel.md

Usage:  python scripts/obs_t_issuelabel.py
"""
import csv, os, sys
from collections import Counter
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ISSUES = os.path.join(ROOT, 'observatory', 'site', 'src', 'data', 'issues.csv')
OUT_MD = os.path.join(ROOT, 'reports', 'obs_t_issuelabel.md')
csv.field_size_limit(10_000_000)

# issue type label (workflow taxonomy) -> coarse bucket comparable to the corpus
TYPE2BUCKET = {
    'text-correction': 'text/surface', 'correction submission': 'text/surface',
    'print change': 'text/surface', 'scan-quality': 'text/surface',
    'markup': 'markup', 'encoding': 'encoding',
    'link-target': 'link/citation', 'link-splitting': 'link/citation',
    'content-enhancement': 'content/sense', 'enhancement': 'content/sense',
    'bug': 'infra/other', 'question': 'infra/other', 'documentation': 'infra/other',
    'help wanted': 'infra/other', 'duplicate': 'infra/other',
}
TYPES = set(TYPE2BUCKET)


def main():
    with open(ISSUES, encoding='utf-8') as f:
        rows = list(csv.DictReader(f))
    type_counts = Counter()
    bucket = Counter()
    n_typed = 0
    for r in rows:
        labs = [x.strip().lower() for x in r['labels'].replace(';', '|').split('|')]
        t = next((x for x in labs if x in TYPES), None)
        if t:
            n_typed += 1
            type_counts[t] += 1
            bucket[TYPE2BUCKET[t]] += 1

    tot = sum(bucket.values()) or 1
    L = []; A = L.append
    A('# Issue-label cross-corroboration (OBS-T)')
    A('')
    A(f'_Generated by `scripts/obs_t_issuelabel.py` from `issues.csv` '
      f'({len(rows):,} issues, {n_typed:,} carrying a recognised type label). The '
      'GitHub issue type taxonomy is independent of, and coarser than, the '
      'microstructure components — read as corroboration, not strict validation._')
    A('')
    A('## Independent issue-type distribution (coarse buckets)')
    A('')
    A('| bucket | issues | share |')
    A('|---|---:|---:|')
    for b, c in bucket.most_common():
        A(f'| {b} | {c:,} | {c/tot:.1%} |')
    A('')
    surface = bucket['text/surface'] + bucket['markup'] + bucket['encoding'] + bucket['link/citation']
    content = bucket['content/sense']
    A(f'**Corroboration.** Text/surface + markup + encoding + link work accounts for '
      f'**{surface/tot:.1%}** of typed issues; content enhancement is only '
      f'**{content/tot:.1%}**. The largest single type is `text-correction` '
      f'({type_counts["text-correction"]:,} issues). This independent human '
      'categorization agrees with the corpus finding (H1) that correction effort is '
      'dominated by surface/text repair rather than content/meaning enhancement.')
    A('')
    A('*Coarse external check; taxonomies differ and the unit is the issue, not the '
      'edit event. Object of analysis in scope per `docs/BOUNDARY_RULES.md`.*')
    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')
    print(f'wrote {OUT_MD}')
    print(f'  typed issues {n_typed}  buckets {bucket.most_common()}')
    print(f'  surface+markup+encoding+link {surface/tot:.1%}  content {content/tot:.1%}')


if __name__ == '__main__':
    main()
