#!/usr/bin/env python3
"""Paradigm-cell coverage — which finite verb cells are corpus-attested per root
(H817 WS1.2, L2 census row).

The VisualDCS paradigm browser (FEATURES_INDEX I10) demonstrates a hand-built 6
roots x 9 tenses x 9 person/number cells widget; this script quantifies the same
question **org-wide** over the DCS full corpus (1,007,361 VERB tokens, 11,096
distinct verb lemmas).

Definition of a "cell": for FINITE verb tokens only (feat_verbform IS NULL — this
excludes participles/converbs/gerundives/infinitives, which are nominal/non-finite
derivatives with their own case/gender/number paradigm, not part of this count) the
5-tuple (tense, mood, voice, person, number) as tagged by the DCS UD pipeline.
`voice` is None for active (UD leaves active implicit) and 'Pass' for passive.

Ceiling (roadmap Part IV risk list — respected, not glossed over): DCS tags
**unaccented** text, so it cannot distinguish verb class I vs VI or class IV vs
the passive formation at the root-class level, and its `Tense=Past` conflates
aorist and perfect. This script counts attested UD-tag combinations as corpus
evidence of *some* form of that cell being used — it does NOT claim to recover the
traditional 10-lakara analysis, and two traditionally-distinct cells that DCS
tags identically will appear here as one attested cell (an undercount of true
paradigm richness, never an overcount).

Output: data/paradigm_cell_coverage_per_root.tsv (root, n_finite_tokens,
        n_distinct_cells, cells attested) + reports/paradigm_cell_coverage.md
        (corpus-wide cell frequency + per-root histogram + top/bottom roots).
Run:    python scripts/paradigm_cell_coverage.py [--db <path to dcs_full.sqlite>]
"""

import argparse
import sqlite3
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

DEFAULT_DB = r"C:\Users\user\Documents\GitHub\VisualDCS\src\DCS-data-2026\dcs_full.sqlite"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=DEFAULT_DB)
    ap.add_argument("--outdir", default=str(Path(__file__).resolve().parent.parent))
    args = ap.parse_args()

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"BLOCKED: DCS sqlite not found at {db_path}", file=sys.stderr)
        sys.exit(1)

    con = sqlite3.connect(str(db_path))
    con.text_factory = str
    cur = con.cursor()

    cur.execute("""
        SELECT lemma, feat_tense, feat_mood, feat_voice, feat_person, feat_number
        FROM token
        WHERE upos = 'VERB' AND feat_verbform IS NULL AND lemma IS NOT NULL
    """)
    rows = cur.fetchall()

    per_root_cells = defaultdict(Counter)
    corpus_cell_freq = Counter()
    for lemma, tense, mood, voice, person, number in rows:
        cell = (tense or "?", mood or "?", voice or "Act", person or "?", number or "?")
        per_root_cells[lemma][cell] += 1
        corpus_cell_freq[cell] += 1

    n_finite_tokens = len(rows)
    n_roots = len(per_root_cells)

    cur.execute("SELECT COUNT(*) FROM token WHERE upos='VERB'")
    n_verb_tokens_total = cur.fetchone()[0]
    cur.execute("SELECT COUNT(DISTINCT lemma) FROM token WHERE upos='VERB'")
    n_verb_lemmas_total = cur.fetchone()[0]

    outdir = Path(args.outdir)
    data_dir = outdir / "data"
    reports_dir = outdir / "reports"
    data_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    # per-root TSV
    tsv_path = data_dir / "paradigm_cell_coverage_per_root.tsv"
    lines = ["root\tfinite_tokens\tdistinct_cells\tcells"]
    for root in sorted(per_root_cells):
        cells = per_root_cells[root]
        total = sum(cells.values())
        cell_str = ";".join(f"{'.'.join(c)}:{n}" for c, n in sorted(cells.items(), key=lambda kv: -kv[1]))
        lines.append(f"{root}\t{total}\t{len(cells)}\t{cell_str}")
    tsv_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # histogram of distinct-cell-count per root
    hist = Counter(len(cells) for cells in per_root_cells.values())

    ranked = sorted(per_root_cells.items(), key=lambda kv: (-len(kv[1]), -sum(kv[1].values())))

    L = []
    L.append("# Paradigm-cell coverage — attested finite verb cells per root (H817 WS1.2)\n")
    L.append("_Created: 13-07-2026 · Last updated: 13-07-2026_\n")
    L.append("_Auto-generated by [scripts/paradigm_cell_coverage.py]"
             "(https://github.com/sanskrit-lexicon/csl-observatory/blob/main/scripts/paradigm_cell_coverage.py) "
             "— Sonnet 5 (`claude-sonnet-5`), H817. Source: "
             "[VisualDCS `dcs_full.sqlite`](https://github.com/gasyoun/VisualDCS). Quantifies "
             "org-wide what the [VisualDCS paradigm browser](https://github.com/gasyoun/VisualDCS) "
             "(FEATURES_INDEX I10) demonstrates on 6 hand-picked roots "
             "([ROADMAP_STATISTICS_ORG_CENSUS_2026_2027.md L2](https://github.com/gasyoun/SanskritLexicography/blob/master/ROADMAP_STATISTICS_ORG_CENSUS_2026_2027.md))._\n")
    L.append("**Ceiling.** DCS tags unaccented text — it cannot split verb class I/VI or "
             "IV/passive at the root-class level, and `Tense=Past` conflates aorist/perfect. "
             "A \"cell\" here is a DCS UD-tag 5-tuple (tense, mood, voice, person, number) on "
             "**finite** tokens only (`feat_verbform IS NULL`); non-finite forms (participle, "
             "converb, gerundive, infinitive) are excluded — they are nominal derivatives with "
             "a different paradigm shape. Two traditionally-distinct lakara cells that collapse "
             "to the same UD tag will undercount here; this method never overcounts.\n")
    L.append(f"**Coverage.** {n_verb_lemmas_total} distinct verb lemmas in corpus "
              f"({n_verb_tokens_total:,} VERB tokens total); **{n_roots}** lemmas have ≥1 "
              f"finite token ({n_finite_tokens:,} finite tokens, "
              f"{round(100*n_finite_tokens/n_verb_tokens_total,1)}% of VERB tokens — the "
              "remainder are participles/converbs/gerundives/infinitives, out of scope here).\n")

    L.append("## 1 · Corpus-wide cell frequency (which finite cells are common vs rare)\n")
    L.append(f"**{len(corpus_cell_freq)}** distinct (tense, mood, voice, person, number) cells "
              "attested anywhere in the corpus.\n")
    L.append("| Cell (tense.mood.voice.person.number) | Tokens | % of finite tokens |")
    L.append("|---|--:|--:|")
    for cell, cnt in corpus_cell_freq.most_common(25):
        pct = round(100 * cnt / n_finite_tokens, 3)
        L.append(f"| {'.'.join(cell)} | {cnt:,} | {pct} |")

    L.append("\n## 2 · Per-root cell-count histogram\n")
    L.append("How many distinct finite cells does a root attest, across how many roots?\n")
    L.append("| Distinct cells attested | Roots |")
    L.append("|--:|--:|")
    for k in sorted(hist, reverse=True):
        L.append(f"| {k} | {hist[k]:,} |")

    L.append("\n## 3 · Top 15 roots by paradigm-cell coverage (most complete finite paradigms)\n")
    L.append("| Root | Distinct cells | Finite tokens |")
    L.append("|---|--:|--:|")
    for root, cells in ranked[:15]:
        L.append(f"| {root} | {len(cells)} | {sum(cells.values()):,} |")

    L.append("\n## 4 · Single-cell roots (attested but only in one finite cell — a "
              "corpus-attestation gap, not necessarily a real paradigm gap)\n")
    single = [r for r, c in per_root_cells.items() if len(c) == 1]
    L.append(f"**{len(single)}** of {n_roots} roots ({round(100*len(single)/n_roots,1)}%) are "
              "attested in only one finite cell in this corpus.\n")

    L.append(f"\nFull per-root table ({len(lines)-1} roots): "
              "[`data/paradigm_cell_coverage_per_root.tsv`]"
              "(https://github.com/sanskrit-lexicon/csl-observatory/blob/main/data/paradigm_cell_coverage_per_root.tsv).\n")
    L.append("_Dr. Mārcis Gasūns_\n")

    report_path = reports_dir / "paradigm_cell_coverage.md"
    report_path.write_text("\n".join(L), encoding="utf-8")

    print(f"Wrote {tsv_path}")
    print(f"Wrote {report_path}")
    print(f"Roots covered: {n_roots}/{n_verb_lemmas_total}, finite tokens: {n_finite_tokens:,}")


if __name__ == "__main__":
    main()
