#!/usr/bin/env python3
"""POS distribution per text (H817 WS1.2, L3 census row).

Reads the DCS full corpus (VisualDCS/src/DCS-data-2026/dcs_full.sqlite — 5,688,416
tokens, 754,726 sentences, 270 texts) and computes the UD-POS (upos) frequency
distribution for every text: token count, distinct-POS count, and the share each
of the 11 UD tags (NOUN/VERB/ADJ/PRON/PART/ADV/CONJ/NUM/SCONJ/ADP/INTJ) takes of
that text's tokens.

Ceiling (roadmap Part IV risk list): DCS is UD-tagged on **unaccented** text, so it
cannot split verb class I/VI or IV/passive, and its Tense=Past conflates aorist and
perfect. This script reports the UD upos tag as-is (a coarse 11-way split) — it does
NOT attempt any finer root-class or tense claim.

Output: data/pos_distribution_per_text.tsv (one row per text x upos) +
        reports/pos_distribution_per_text.md (summary + top/bottom texts by verb
        share, table with CSV-download-style full row count).
Run:    python scripts/pos_distribution_per_text.py [--db <path to dcs_full.sqlite>]
"""

import argparse
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

DEFAULT_DB = r"C:\Users\user\Documents\GitHub\VisualDCS\src\DCS-data-2026\dcs_full.sqlite"

UPOS_TAGS = ["NOUN", "VERB", "ADJ", "PRON", "PART", "ADV", "CONJ", "NUM",
             "SCONJ", "ADP", "INTJ"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=DEFAULT_DB)
    ap.add_argument("--outdir", default=str(Path(__file__).resolve().parent.parent))
    args = ap.parse_args()

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"BLOCKED: DCS sqlite not found at {db_path}", file=sys.stderr)
        sys.exit(1)

    con = sqlite3.connect(str(db_path))
    con.text_factory = str
    cur = con.cursor()

    cur.execute("""
        SELECT t.name, tk.upos, COUNT(*)
        FROM token tk
        JOIN sentence s ON tk.sentence_id = s.id
        JOIN chapter c ON s.chapter_id = c.chapter_id
        JOIN text t ON c.text_id = t.text_id
        GROUP BY t.name, tk.upos
    """)
    rows = cur.fetchall()

    per_text = defaultdict(lambda: defaultdict(int))
    for name, upos, cnt in rows:
        per_text[name][upos or "NULL"] += cnt

    cur.execute("SELECT COUNT(*) FROM text")
    n_texts_total = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM token")
    n_tokens_total = cur.fetchone()[0]

    outdir = Path(args.outdir)
    data_dir = outdir / "data"
    reports_dir = outdir / "reports"
    data_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    # TSV: one row per text x upos
    tsv_path = data_dir / "pos_distribution_per_text.tsv"
    all_tags = sorted({tag for d in per_text.values() for tag in d})
    tsv_lines = ["text\tupos\tcount\tpct_of_text"]
    for name in sorted(per_text):
        total = sum(per_text[name].values())
        for tag in all_tags:
            cnt = per_text[name].get(tag, 0)
            if cnt:
                pct = round(100 * cnt / total, 3)
                tsv_lines.append(f"{name}\t{tag}\t{cnt}\t{pct}")
    tsv_path.write_text("\n".join(tsv_lines) + "\n", encoding="utf-8")

    # summary table: text, total tokens, distinct upos, verb%, noun%
    summary_rows = []
    for name in per_text:
        total = sum(per_text[name].values())
        verb_pct = 100 * per_text[name].get("VERB", 0) / total if total else 0
        noun_pct = 100 * per_text[name].get("NOUN", 0) / total if total else 0
        distinct = sum(1 for tag in all_tags if per_text[name].get(tag, 0) > 0)
        summary_rows.append((name, total, distinct, verb_pct, noun_pct))
    summary_rows.sort(key=lambda r: -r[1])

    corpus_totals = defaultdict(int)
    for d in per_text.values():
        for tag, cnt in d.items():
            corpus_totals[tag] += cnt

    L = []
    L.append("# POS distribution per text — DCS full corpus (H817 WS1.2)\n")
    L.append("_Created: 13-07-2026 · Last updated: 13-07-2026_\n")
    L.append("_Auto-generated by [scripts/pos_distribution_per_text.py]"
             "(https://github.com/sanskrit-lexicon/csl-observatory/blob/main/scripts/pos_distribution_per_text.py) "
             "— Sonnet 5 (`claude-sonnet-5`), H817. Source: "
             "[VisualDCS `dcs_full.sqlite`](https://github.com/gasyoun/VisualDCS) "
             "(5,688,416 tokens · 754,726 sentences · 270 texts, per "
             "[ROADMAP_STATISTICS_ORG_CENSUS_2026_2027.md L3](https://github.com/gasyoun/SanskritLexicography/blob/master/ROADMAP_STATISTICS_ORG_CENSUS_2026_2027.md))._\n")
    L.append(f"**Ceiling.** DCS UD-tagging runs on unaccented text — it cannot split verb "
              "class I/VI or IV/passive, and `Tense=Past` conflates aorist/perfect. This "
              "census reports the coarse 11-way UD `upos` tag only; it makes no finer "
              "root-class or tense claim (roadmap Part IV risk list).\n")
    L.append(f"**Coverage.** {n_texts_total} texts in the DB, **{len(per_text)}** with at "
              f"least one tagged token, **{n_tokens_total:,}** tokens total.\n")

    L.append("## 1 · Corpus-wide UD-POS distribution\n")
    L.append("| upos | tokens | % of corpus |")
    L.append("|---|--:|--:|")
    for tag, cnt in sorted(corpus_totals.items(), key=lambda kv: -kv[1]):
        pct = round(100 * cnt / n_tokens_total, 2)
        L.append(f"| {tag} | {cnt:,} | {pct} |")

    L.append("\n## 2 · Top 20 texts by token count (with verb%/noun% share)\n")
    L.append("| Text | Tokens | Distinct upos | VERB % | NOUN % |")
    L.append("|---|--:|--:|--:|--:|")
    for name, total, distinct, verb_pct, noun_pct in summary_rows[:20]:
        L.append(f"| {name} | {total:,} | {distinct} | {round(verb_pct,2)} | {round(noun_pct,2)} |")

    L.append("\n## 3 · Most verb-dense and most noun-dense texts (≥1,000 tokens)\n")
    filtered = [r for r in summary_rows if r[1] >= 1000]
    by_verb = sorted(filtered, key=lambda r: -r[3])[:10]
    by_noun = sorted(filtered, key=lambda r: -r[4])[:10]
    L.append("Most verb-dense:\n")
    L.append("| Text | Tokens | VERB % |")
    L.append("|---|--:|--:|")
    for name, total, distinct, verb_pct, noun_pct in by_verb:
        L.append(f"| {name} | {total:,} | {round(verb_pct,2)} |")
    L.append("\nMost noun-dense:\n")
    L.append("| Text | Tokens | NOUN % |")
    L.append("|---|--:|--:|")
    for name, total, distinct, verb_pct, noun_pct in by_noun:
        L.append(f"| {name} | {total:,} | {round(noun_pct,2)} |")

    L.append(f"\nFull per-text x per-upos table ({len(tsv_lines)-1} rows): "
              "[`data/pos_distribution_per_text.tsv`]"
              "(https://github.com/sanskrit-lexicon/csl-observatory/blob/main/data/pos_distribution_per_text.tsv).\n")
    L.append("_Dr. Mārcis Gasūns_\n")

    report_path = reports_dir / "pos_distribution_per_text.md"
    report_path.write_text("\n".join(L), encoding="utf-8")

    print(f"Wrote {tsv_path}")
    print(f"Wrote {report_path}")
    print(f"Texts covered: {len(per_text)}/{n_texts_total}, tokens: {n_tokens_total:,}")


if __name__ == "__main__":
    main()
