"""
render_reports.py — render Markdown dashboards from computed metrics.

Reads:  data/{summary,contributors,repo_metrics,timeline,cross_repo}.json
Writes: reports/{dashboard,contributors,timeline,coverage}.md
"""
import json, sys, datetime
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

DATA = Path(__file__).resolve().parent.parent / 'data'
REPORTS = Path(__file__).resolve().parent.parent / 'reports'

TYPE_ORDER = ['link-target','link-splitting','markup','text-correction',
              'content-enhancement','encoding','scan-quality','bug','question']


def load(name): return json.loads((DATA / name).read_text(encoding='utf-8'))


def fmt_int(n): return f'{n:,}'.replace(',', ',')


def render_dashboard(summary, repos_metrics, timeline, cross, contributors):
    L = []
    L.append('# CDSL ecosystem dashboard')
    L.append('')
    L.append(f'**Snapshot date**: {summary["snapshot_date"]} · **Fetched**: {summary["fetched_at"]}\n')

    L.append('## Headline numbers\n')
    L.append('| Metric | Value |')
    L.append('|---|---|')
    L.append(f'| Repositories in `sanskrit-lexicon` | {fmt_int(summary["repos_count"])} |')
    L.append(f'| Repositories with issues enabled | {fmt_int(summary["repos_with_issues"])} |')
    L.append(f'| Total issues (incl. closed) | {fmt_int(summary["total_issues"])} |')
    L.append(f'| Total pull requests | {fmt_int(summary["total_pull_requests"])} |')
    L.append(f'| Total commits in default branches | {fmt_int(summary["total_commits"])} |')
    L.append(f'| Distinct contributors (commit authors + issue authors) | {fmt_int(len(contributors))} |')
    L.append(f'| Triaged repositories (taxonomy applied) | {fmt_int(len(cross["triaged_repos"]))} |')
    L.append('')

    L.append('## Issue type distribution across all triaged repos\n')
    L.append('| Type | Count | % of typed issues |')
    L.append('|---|---:|---:|')
    total = sum(cross['type_totals'].values()) or 1
    for t in TYPE_ORDER:
        n = cross['type_totals'].get(t, 0)
        L.append(f'| `{t}` | {n} | {100*n/total:.1f} % |')
    L.append('')
    L.append('```mermaid')
    L.append('pie title Issue type distribution')
    for t in TYPE_ORDER:
        n = cross['type_totals'].get(t, 0)
        if n: L.append(f'    "{t}" : {n}')
    L.append('```')
    L.append('')

    L.append('## Type × repository heatmap\n')
    triaged = cross['triaged_repos']
    if triaged:
        L.append('| Type | ' + ' | '.join(triaged) + ' | total |')
        L.append('|---|' + '---:|' * (len(triaged) + 1))
        for t in TYPE_ORDER:
            row = cross['type_x_repo'].get(t, {})
            cells = [str(row.get(r, 0)) for r in triaged]
            total_t = sum(int(c) for c in cells)
            L.append(f'| `{t}` | ' + ' | '.join(cells) + f' | **{total_t}** |')
    L.append('')

    L.append('## Activity by year\n')
    L.append('| Year | Commits | Issues opened | Issues closed |')
    L.append('|---|---:|---:|---:|')
    years = sorted(set(timeline['commits_by_year']) |
                   set(timeline['issues_created_by_year']) |
                   set(timeline['issues_closed_by_year']))
    for y in years:
        c = timeline['commits_by_year'].get(y, 0)
        io = timeline['issues_created_by_year'].get(y, 0)
        ic = timeline['issues_closed_by_year'].get(y, 0)
        L.append(f'| {y} | {c} | {io} | {ic} |')
    L.append('')

    L.append('## Top contributors (by commits)\n')
    L.append('| Real name | GitHub | Role | Commits | Repos | Span | Lines + / − |')
    L.append('|---|---|---|---:|---:|---|---:|')
    for c in contributors[:20]:
        name = c.get('real_name') or c['login']
        sf = (c.get('span_first') or '-')[:7]
        sl = (c.get('span_last') or '-')[:7]
        L.append(f'| {name} | [@{c["login"]}](https://github.com/{c["login"]}) | '
                 f'{c.get("role", "-")} | {c["commits_total"]:,} | '
                 f'{c["repos_touched_count"]} | {sf} → {sl} | '
                 f'+{c["additions_total"]:,} / −{c["deletions_total"]:,} |')
    L.append('')

    L.append('## Per-repository summary\n')
    L.append('| Repo | Commits | Issues | Open | Closed | Triaged | First | Last |')
    L.append('|---|---:|---:|---:|---:|:---:|---|---|')
    for rm in sorted(repos_metrics, key=lambda r: -r['commits_count']):
        if rm.get('archived'): continue
        first = (rm.get('first_commit') or '-')[:10]
        last = (rm.get('last_commit') or '-')[:10]
        triaged = '✓' if rm.get('triaged') else ''
        L.append(f'| [{rm["name"]}](https://github.com/sanskrit-lexicon/{rm["name"]}) | '
                 f'{rm["commits_count"]:,} | {rm["issues_total"]} | '
                 f'{rm["issues_open"]} | {rm["issues_closed"]} | {triaged} | '
                 f'{first} | {last} |')
    L.append('')

    L.append('---')
    L.append('*Generated by `scripts/render_reports.py`. Data: `data/snapshots/'
             f'{summary["snapshot_date"]}/`. License: data CC BY-SA 4.0.*')
    return '\n'.join(L) + '\n'


def render_contributors(contributors):
    L = []
    L.append('# Contributors')
    L.append('')
    L.append('Each contributor section gives canonical identity, GitHub login, role, span '
             'of activity, repositories touched, and headline metrics. ORCIDs marked '
             '`PLACEHOLDER-…` are awaiting registration; please open a PR to fill them in.')
    L.append('')
    role_order = ['lead', 'maintainer', 'core', 'contributor', 'occasional']
    by_role = {r: [] for r in role_order}
    by_role['other'] = []
    for c in contributors:
        r = c.get('role', 'contributor')
        by_role.setdefault(r, []).append(c)
    for r in role_order + ['other']:
        if not by_role.get(r): continue
        L.append(f'## {r.title()} ({len(by_role[r])})\n')
        for c in by_role[r]:
            name = c.get('real_name') or c['login']
            L.append(f'### {name}\n')
            L.append(f'- **GitHub**: [@{c["login"]}](https://github.com/{c["login"]})')
            if c.get('orcid'):
                if 'PLACEHOLDER' in c['orcid']:
                    L.append(f'- **ORCID**: *(awaiting)*')
                else:
                    L.append(f'- **ORCID**: [{c["orcid"]}](https://orcid.org/{c["orcid"]})')
            if c.get('affiliation'): L.append(f'- **Affiliation**: {c["affiliation"]}')
            sf = c.get("span_first") or "—"
            sl = c.get("span_last") or "—"
            yrs = c.get("span_years")
            span = f'{sf} → {sl}' + (f' ({yrs} years)' if yrs else '')
            L.append(f'- **Active span**: {span}')
            L.append(f'- **Commits**: {c["commits_total"]:,} '
                     f'across {c["repos_touched_count"]} repos')
            L.append(f'- **Issues created**: {c["issues_created"]}')
            L.append(f'- **Lines changed**: +{c["additions_total"]:,} '
                     f'/ −{c["deletions_total"]:,}')
            if c.get('notes'): L.append(f'- **Role notes**: {c["notes"]}')
            top_repos = list(c['commits_per_repo'].items())[:8]
            if top_repos:
                L.append(f'- **Top repositories** (by commits): ' +
                         ', '.join(f'`{r}` ({n})' for r, n in top_repos))
            L.append('')
    return '\n'.join(L) + '\n'


def render_timeline(timeline, contributors):
    L = []
    L.append('# Activity timeline')
    L.append('')
    L.append('## Contributor active spans\n')
    L.append('Each bar shows a contributor\'s first to last commit across the ecosystem.\n')
    L.append('```mermaid')
    L.append('gantt')
    L.append('    title Contributor active spans (first → last commit)')
    L.append('    dateFormat YYYY-MM-DD')
    L.append('    axisFormat %Y')
    role_order = ['lead', 'maintainer', 'core', 'contributor', 'occasional']
    for role in role_order:
        people = [c for c in contributors if c.get('role') == role and c.get('span_first')]
        if not people: continue
        L.append(f'    section {role.title()}')
        for c in people[:25]:
            name = (c.get('real_name') or c['login']).replace(':', ' ')
            L.append(f'    {name} :{c["span_first"]}, {c["span_last"]}')
    L.append('```')
    L.append('')
    L.append('## Commits per year\n')
    L.append('| Year | Commits |')
    L.append('|---|---:|')
    for y, n in timeline['commits_by_year'].items():
        L.append(f'| {y} | {n:,} |')
    L.append('')
    return '\n'.join(L) + '\n'


def render_coverage(repos_metrics):
    L = []
    L.append('# Coverage and provenance')
    L.append('')
    L.append('This report tracks **dictionary entry counts**, **scan coverage**, '
             '**markup ratios**, and **license declarations** per repository. '
             'Headword counts are derived from source files in `csl-orig` where '
             'available; missing values indicate the file pattern was not yet '
             'detected by `pull_data.py` and need a coverage-pass.')
    L.append('')
    L.append('## License posture\n')
    L.append('| Repo | License | Issues triaged |')
    L.append('|---|---|:---:|')
    for rm in sorted(repos_metrics, key=lambda r: r['name']):
        if rm.get('archived'): continue
        lic = rm.get('license') or '*(none)*'
        triaged = '✓' if rm.get('triaged') else ''
        L.append(f'| {rm["name"]} | {lic} | {triaged} |')
    L.append('')
    L.append('## Headword counts\n')
    L.append('*Coverage data not yet implemented; see issue tracker.*\n')
    return '\n'.join(L) + '\n'


def main():
    REPORTS.mkdir(parents=True, exist_ok=True)
    summary = load('summary.json')
    contributors = load('contributors.json')
    repos_metrics = load('repo_metrics.json')
    timeline = load('timeline.json')
    cross = load('cross_repo.json')

    (REPORTS / 'dashboard.md').write_text(
        render_dashboard(summary, repos_metrics, timeline, cross, contributors), encoding='utf-8')
    (REPORTS / 'contributors.md').write_text(
        render_contributors(contributors), encoding='utf-8')
    (REPORTS / 'timeline.md').write_text(
        render_timeline(timeline, contributors), encoding='utf-8')
    (REPORTS / 'coverage.md').write_text(
        render_coverage(repos_metrics), encoding='utf-8')

    print('reports/ written:')
    for p in sorted(REPORTS.glob('*.md')):
        print(f'  {p.name}: {p.stat().st_size:,} bytes')

if __name__ == '__main__':
    main()
