#!/usr/bin/env python3
"""Repository-health audit for the sanskrit-lexicon org.

Operates offline on the already-extracted observatory data
(`observatory/site/src/data/repos.csv`) — no GitHub calls, fully
reproducible. Flags repository-level hygiene gaps that are cheap to fix and
matter for a FAIR, citable digitisation ecosystem:

* **License** — none at all vs. an unrecognised license file (GitHub
  `NOASSERTION`, i.e. a LICENSE exists but its SPDX id can't be matched) vs.
  a recognised SPDX license.
* **Default branch** — `master` (legacy) vs. `main` vs. other (`gh-pages`).
* **Description** — missing one-line repo description.
* **Cleanup candidates** — `temp_*` / `test_*` / legacy repos that are live
  (not archived) but look disposable.
* **Staleness** — days since the last push.

Outputs
-------
* `reports/repo_health.md`                    — human-readable finding
* `observatory/site/src/data/repo_health.csv` — per-repo flags for the site

Usage:  python scripts/repo_health.py
"""
import csv, os, sys
from collections import Counter
from datetime import datetime, timezone
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, 'observatory', 'site', 'src', 'data')
REPOS = os.path.join(DATA, 'repos.csv')
OUT_MD = os.path.join(ROOT, 'reports', 'repo_health.md')
OUT_CSV = os.path.join(DATA, 'repo_health.csv')

STALE_DAYS = 180   # no push in this many days = stale
CLEANUP_PREFIXES = ('temp_', 'test_')
CLEANUP_NAMES = {'santamlegacy'}


def days_since(iso, now):
    if not iso:
        return None
    return (now - datetime.fromisoformat(iso.replace('Z', '+00:00'))).days


def license_class(lic):
    lic = (lic or '').strip()
    if not lic:
        return 'none'
    if lic == 'NOASSERTION':
        return 'unrecognised'
    return 'recognised'


def main():
    now = datetime.now(timezone.utc)
    rows = []
    with open(REPOS, encoding='utf-8') as f:
        for r in csv.DictReader(f):
            lic = license_class(r['license'])
            branch = r['default_branch'].strip()
            name = r['repo']
            age = days_since(r['pushed_at'], now)
            cleanup = (name.startswith(CLEANUP_PREFIXES) or name in CLEANUP_NAMES)
            flags = []
            if lic == 'none':
                flags.append('no-license')
            elif lic == 'unrecognised':
                flags.append('license-unrecognised')
            if branch == 'master':
                flags.append('legacy-branch')
            elif branch not in ('main', 'master'):
                flags.append(f'branch:{branch}')
            if not r['description'].strip():
                flags.append('no-description')
            if cleanup and r['archived'].strip().lower() != 'true':
                flags.append('cleanup-candidate')
            if age is not None and age > STALE_DAYS:
                flags.append('stale')
            rows.append({
                'repo': name,
                'license_class': lic,
                'license': (r['license'] or '').strip(),
                'default_branch': branch,
                'open_issues': int(r['open_issues'] or 0),
                'days_since_push': age if age is not None else '',
                'has_description': 'no' if not r['description'].strip() else 'yes',
                'archived': r['archived'].strip().lower(),
                'flag_count': len(flags),
                'flags': '|'.join(flags),
            })

    n = len(rows)
    lic_counts = Counter(r['license_class'] for r in rows)
    branch_counts = Counter(r['default_branch'] for r in rows)
    no_desc = [r for r in rows if r['has_description'] == 'no']
    cleanup = [r for r in rows if 'cleanup-candidate' in r['flags']]
    stale = [r for r in rows if 'stale' in r['flags']]
    legacy = [r for r in rows if r['default_branch'] == 'master']
    clean = [r for r in rows if r['flag_count'] == 0]

    # ---- per-repo CSV ----
    with open(OUT_CSV, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=['repo', 'license_class', 'license',
            'default_branch', 'open_issues', 'days_since_push', 'has_description',
            'archived', 'flag_count', 'flags'])
        w.writeheader()
        for r in sorted(rows, key=lambda x: (-x['flag_count'], x['repo'])):
            w.writerow(r)

    # ---- report ----
    L = []; A = L.append
    A('# Repository-health audit')
    A('')
    A(f'_Generated by `scripts/repo_health.py` from '
      f'`observatory/site/src/data/repos.csv` (offline, reproducible). '
      f'{n} non-fork repositories, {now:%Y-%m-%d}._')
    A('')
    A('## Headline')
    A('')
    A('| Metric | Value |')
    A('|---|---:|')
    A(f'| Repositories audited | {n} |')
    A(f'| **No license at all** | **{lic_counts["none"]} / {n}** ({100*lic_counts["none"]//n}%) |')
    A(f'| License file unrecognised (`NOASSERTION`) | {lic_counts["unrecognised"]} / {n} |')
    A(f'| Recognised SPDX license | {lic_counts["recognised"]} / {n} |')
    A(f'| Default branch `master` (legacy) | {len(legacy)} / {n} |')
    A(f'| Missing a description | {len(no_desc)} / {n} |')
    A(f'| Live cleanup candidates (`temp_*`/`test_*`/legacy) | {len(cleanup)} |')
    A(f'| Stale (no push in {STALE_DAYS}+ days) | {len(stale)} |')
    A(f'| Clean (no flags) | {len(clean)} / {n} |')
    A('')
    A('## Licensing')
    A('')
    A('After the RH1 license rollout (2026-06), almost every repository carries '
      'a recognised SPDX license — code/tooling under GPL-3.0, dictionary and '
      'data repositories under CC-BY-SA-4.0, mixed repos split (data '
      'CC-BY-SA-4.0 + `licenses/GPL-3.0.txt`). The `NOASSERTION` block is '
      'cleared. The only repositories still without a license are the RH3 '
      'archive/temp candidates, intentionally excluded until that cleanup runs. '
      'See `docs/RH1_LICENSE_ROLLOUT_LOG.md`.')
    A('')
    A('| License state | Count | Repositories |')
    A('|---|---:|---|')
    for cls, label in [('none', 'No license'),
                       ('unrecognised', 'Unrecognised (`NOASSERTION`)'),
                       ('recognised', 'Recognised SPDX')]:
        repos = sorted(r['repo'] for r in rows if r['license_class'] == cls)
        shown = ', '.join(f'`{x}`' for x in repos)
        A(f'| {label} | {len(repos)} | {shown} |')
    A('')
    A('## Default branch')
    A('')
    A('Branch naming is inconsistent across the org — a mix of `master`, '
      '`main`, and `gh-pages` complicates tooling, CI defaults, and runbooks.')
    A('')
    A('| Default branch | Count |')
    A('|---|---:|')
    for br, c in branch_counts.most_common():
        A(f'| `{br}` | {c} |')
    A('')
    A('## Missing a description')
    A('')
    if no_desc:
        A(', '.join(f'`{r["repo"]}`' for r in sorted(no_desc, key=lambda x: x['repo'])) + '.')
    else:
        A('None — every repository has a description.')
    A('')
    A('## Cleanup candidates (live, not archived)')
    A('')
    A('Disposable-looking repositories that are still active. Consider '
      'archiving so they drop out of contributor/issue metrics and search.')
    A('')
    A('| Repository | Open issues | Days since push |')
    A('|---|---:|---:|')
    for r in sorted(cleanup, key=lambda x: x['repo']):
        A(f'| {r["repo"]} | {r["open_issues"]} | {r["days_since_push"]} |')
    A('')
    A('## Staleness')
    A('')
    if stale:
        A(f'Repositories with no push in {STALE_DAYS}+ days:')
        A('')
        A('| Repository | Days since push |')
        A('|---|---:|')
        for r in sorted(stale, key=lambda x: -(x['days_since_push'] or 0)):
            A(f'| {r["repo"]} | {r["days_since_push"]} |')
    else:
        oldest = max((r for r in rows if r['days_since_push'] != ''),
                     key=lambda x: x['days_since_push'])
        A(f'No stale repositories — every repo was pushed within the last '
          f'{STALE_DAYS} days. The most idle is `{oldest["repo"]}` at '
          f'{oldest["days_since_push"]} days. The ecosystem is uniformly '
          'maintained; abandonment is not the risk here (concentration is — '
          'see `reports/bus_factor.md`).')
    A('')
    A('## Repositories by flag count')
    A('')
    A('| Repository | Flags | License | Branch | Open issues | Days idle |')
    A('|---|---|---|---|---:|---:|')
    for r in sorted(rows, key=lambda x: (-x['flag_count'], x['repo'])):
        A(f'| {r["repo"]} | {r["flags"] or "—"} | {r["license"] or "—"} | '
          f'{r["default_branch"]} | {r["open_issues"]} | {r["days_since_push"]} |')
    A('')
    A('*Object of analysis: GitHub repositories — in scope per '
      '`docs/BOUNDARY_RULES.md`.*')

    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')

    print(f'wrote {OUT_MD}')
    print(f'wrote {OUT_CSV}')
    print(f'  repos: {n}   no-license: {lic_counts["none"]}   '
          f'NOASSERTION: {lic_counts["unrecognised"]}   recognised: {lic_counts["recognised"]}')
    print(f'  legacy-branch (master): {len(legacy)}   no-description: {len(no_desc)}   '
          f'cleanup: {len(cleanup)}   stale: {len(stale)}   clean: {len(clean)}')


if __name__ == '__main__':
    main()
