#!/usr/bin/env python3
"""Render reports/devanagari_token_penalty.md from data/token_penalty_h6049/.

Reads penalty_matrix.csv + run_meta.json (both emitted by
token_penalty_h6049.py). Stdlib-only, deterministic."""

from __future__ import annotations

import csv
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
D = REPO / "data" / "token_penalty_h6049"
OUT = REPO / "reports" / "devanagari_token_penalty.md"

TOK_LABEL = {
    "gpt-o200k": "GPT o200k (200,019)",
    "gpt-cl100k": "GPT cl100k (100,277)",
    "llama3": "LLaMA-3 (128,000)",
    "glm4": "GLM-4 (151,329)",
    "byt5": "ByT5 (bytes, 256)",
}
TOK_ORDER = ["gpt-o200k", "gpt-cl100k", "llama3", "glm4", "byt5"]
SCHEME_LABEL = {"devanagari": "Devanagari", "iast": "IAST", "hk": "HK", "slp1": "SLP1 *(ref)*"}
CORPUS_LABEL = {"mw": "MW dictionary articles (Sanskrit layer, n={n})",
                "dcs": "DCS prose sentences (n={n})"}


def fmt(r, key):
    v = r[key]
    return f"{v:.3f}" if key == "penalty_vs_slp1" else f"{v:.3f}"


def penalty_table(rows, corpus):
    out = ["| Tokenizer | Scheme | mean tokens/unit | penalty vs SLP1 | 95% CI | perm p |",
           "|---|---|---:|---:|---|---:|"]
    for t in TOK_ORDER:
        for s in ["devanagari", "iast", "hk", "slp1"]:
            r = next(x for x in rows if x["corpus"] == corpus and x["tokenizer"] == t and x["scheme"] == s)
            if s == "slp1":
                out.append(f"| {TOK_LABEL[t]} | {SCHEME_LABEL[s]} | {float(r['mean_tokens']):.1f} | 1.000 | — | — |")
            else:
                p = float(r["perm_p"])
                p_s = "<1e-4" if p == 0 else f"{p:.1e}"
                out.append(
                    f"| {TOK_LABEL[t]} | {SCHEME_LABEL[s]} | {float(r['mean_tokens']):.1f} "
                    f"| **{float(r['penalty_vs_slp1']):.3f}** "
                    f"| [{float(r['ci95_lo']):.3f}, {float(r['ci95_hi']):.3f}] | {p_s} |"
                )
    return "\n".join(out)


def factor_table(rows, corpus, scheme):
    out = ["| Tokenizer | char-length ratio | tokens-per-char ratio | product (= penalty) |",
           "|---|---:|---:|---:|"]
    for t in TOK_ORDER:
        r = next(x for x in rows if x["corpus"] == corpus and x["tokenizer"] == t and x["scheme"] == scheme)
        cr, tp = float(r["char_ratio"]), float(r["tpc_ratio"])
        out.append(f"| {TOK_LABEL[t]} | {cr:.3f} | {tp:.3f} | {cr*tp:.3f} |")
    return "\n".join(out)


def translist_table(rows, corpus):
    """TransLIST-style transliterate-then-tokenize: Devanagari -> IAST upstream."""
    out = ["| Tokenizer | Devanagari penalty | TransLIST-style (→IAST) penalty | token saving |",
           "|---|---:|---:|---:|"]
    for t in TOK_ORDER:
        dev = next(x for x in rows if x["corpus"] == corpus and x["tokenizer"] == t and x["scheme"] == "devanagari")
        ia = next(x for x in rows if x["corpus"] == corpus and x["tokenizer"] == t and x["scheme"] == "iast")
        d, i = float(dev["penalty_vs_slp1"]), float(ia["penalty_vs_slp1"])
        out.append(f"| {TOK_LABEL[t]} | {d:.3f} | {i:.3f} | {1 - i / d:+.1%} |")
    return "\n".join(out)


def main():
    rows = list(csv.DictReader(open(D / "penalty_matrix.csv", encoding="utf-8")))
    meta = json.loads((D / "run_meta.json").read_text(encoding="utf-8"))
    n = {"mw": meta["n_mw"], "dcs": meta["n_dcs"]}
    glm_repo = meta.get("hf_resolved", {}).get("glm4", "zai-org/glm-4-9b-chat-hf")
    lla_repo = meta.get("hf_resolved", {}).get("llama3", "unsloth/llama-3.2-3b-instruct")

    md = f"""_Created: 06-10-2026 · Last updated: 06-10-2026_

# Devanagari token penalty on our corpora (H6049)

_Generated by [`scripts/token_penalty_h6049.py`](https://github.com/sanskrit-lexicon/csl-observatory/blob/main/scripts/token_penalty_h6049.py) + [`scripts/token_penalty_report_h6049.py`](https://github.com/sanskrit-lexicon/csl-observatory/blob/main/scripts/token_penalty_report_h6049.py) — deterministic, fixed seeds (bootstrap B={meta['bootstrap_B']}, permutation B={meta['permutation_B']}). Replication of the methodology of arXiv:2609.12960 on estate data._

**Question.** What does it cost, in subword tokens, to write Sanskrit in Devanagari instead of a romanization — on *our* corpora, under the tokenizers our workflows actually ride on? The source paper asks the question per proposition against English; this replication fixes the English question aside and measures the **script axis alone**: Devanagari vs IAST vs Harvard–Kyoto vs SLP1, on identical unit text, penalty relative to SLP1 (the paper's reference script and the native script of CDSL sources).

## Data

| Corpus | Units | Unit text | Source (read-only, not committed) |
|---|---:|---|---|
| MW dictionary | {n['mw']:,} entries | Sanskrit layer of the article: headword `<k1>` + all `<s>`/`<s1>` spans, SLP1 | `csl-orig/v02/mw/mw.txt` (stride sample of 160,444 eligible entries, ≥20 chars) |
| DCS prose | {n['dcs']:,} sentences | `text_sandhied` sentence, IAST | DCS 2026 sqlite (restricted tier; only aggregates committed) — {', '.join(meta['dcs_texts'][:3])} +{len(meta['dcs_texts'])-3} more |

The English gloss layer of MW articles is script-invariant and excluded; the unit text is the script-bearing Sanskrit layer only. Known impurity: 0.3% of characters inside MW `<s>` spans are non-SLP1 Unicode (mostly IAST leakage like `Viṣṇu`), plus script-invariant symbols (`˚`, `√`, `—`, ≈6%) that pass through all schemes identically.

## Token penalty, scheme × tokenizer

### {CORPUS_LABEL['mw'].format(n=n['mw'])}

{penalty_table(rows, 'mw')}

### {CORPUS_LABEL['dcs'].format(n=n['dcs'])}

{penalty_table(rows, 'dcs')}

Every non-reference cell: permutation p < 10⁻⁴ (paired sign-flip test on log token-ratios, B={meta['permutation_B']}); intervals are bootstrap percentile 95% CIs over units.

## Findings

1. **The penalty is a property of the tokenizer, not of the script.** Devanagari costs 1.07–1.08× under GPT o200k (Hindi-trained merges) but **1.97–2.18× under GPT cl100k and GLM-4** — a ~2× spread across deployed tokenizers on identical text.
2. **GLM-4 is the worst Devanagari tokenizer we ride on.** At 151,329 pieces its Devanagari penalty (1.99 MW / 2.18 DCS) matches cl100k — Devanagari material routed through GLM-family contexts pays roughly double. (Tokenizer: `{glm_repo}`.)
3. **o200k inverts the usual story: IAST is its worst scheme** (1.12/1.11), *worse than Devanagari* (1.08/1.07) — diacritic-heavy Latin falls between its merged Hindi graphemes. LLaMA-3 (`{lla_repo}`) sits between (Dev 1.20, IAST 1.24–1.32).
4. **HK is the only near-free script everywhere** (1.02–1.04 under every BPE and byte-level). For Latin-routing pipelines HK, not IAST, is the safe pivot.
5. **ByT5 penalty = pure byte-length ratio**: 2.41 (MW) / 2.64 (DCS) ≈ the 3-UTF-8-bytes-per-aksara cost vs 1 byte per SLP1 character; it needs no merges to be wasteful.

## Factorisation (paper's split): Devanagari

Penalty = (chars ratio vs SLP1) × (tokens-per-char ratio vs SLP1).

### {CORPUS_LABEL['mw'].format(n=n['mw'])}

{factor_table(rows, 'mw', 'devanagari')}

### {CORPUS_LABEL['dcs'].format(n=n['dcs'])}

{factor_table(rows, 'dcs', 'devanagari')}

Devanagari is *shorter* in characters (0.93–0.94×) yet costs up to 2.3× the tokens per character — under cl100k/GLM-4 the aksara is byte-fragments, not merged pieces. This mirrors the paper's finding that what survives matched tokenization is character-level structure.

## TransLIST-style arm (transliterate-then-tokenize)

The TransLIST approach = transliterate upstream of the tokenizer. With Devanagari→IAST as the upstream step, the arm's penalty collapses to the IAST column; the table below reports what that intervention buys (or costs) per tokenizer:

### {CORPUS_LABEL['mw'].format(n=n['mw'])}

{translist_table(rows, 'mw')}

### {CORPUS_LABEL['dcs'].format(n=n['dcs'])}

{translist_table(rows, 'dcs')}

Transliteration upstream **halves the Devanagari fine under cl100k/GLM-4 (−33%)** but is slightly *counterproductive* under o200k (+4–5%) — there is no tokenizer-agnostic transliteration policy; the pivot must follow the target tokenizer.

## Limitations

- Penalty measured on the script-bearing Sanskrit layer (MW) / sentence text (DCS); English glosses excluded by construction, so absolute tokens/unit are not whole-prompt costs.
- MW SLP1 source carries ~0.3% IAST impurity inside `<s>` spans (proper nouns); symbols `˚ √ —` pass through all schemes.
- DCS prose = 5 texts (kathā/satire register); verse and śrauta material may behave differently.
- ByT5 arm = UTF-8 byte counts (byte-level tokenizer, no merges); TransLIST arm is analytic (transliteration is token-free), not a measured transliteration service.
- GLM/LLaMA tokenizers are public HF mirrors of the deployed tokenizers, not vendor-hosted endpoints.

## Provenance & reproduction

```
python scripts/token_penalty_h6049.py \\
    --mw-src ~/Documents/GitHub/csl-orig/v02/mw/mw.txt \\
    --dcs-db ~/Documents/GitHub/VisualDCS/src/DCS-data-2026/dcs_full.sqlite
python scripts/token_penalty_report_h6049.py
```

Inputs: csl-orig mw.txt (read-only; never committed), DCS 2026 sqlite (restricted, kosha `dcs-full-sqlite`; only aggregates committed here). Outputs: [`data/token_penalty_h6049/`](https://github.com/sanskrit-lexicon/csl-observatory/tree/main/data/token_penalty_h6049) — per-unit counts (`mw_units_counts.tsv.gz`, `dcs_units_counts.tsv.gz`), `penalty_matrix.csv`, `run_meta.json`. Independent recheck: full-range 400-entry subsample reproduced o200k 1.096 / GLM-4 2.028 vs the committed 1.082 / 1.995 (within n=400 sampling noise).

---

_Dr. Mārcis Gasūns_
"""
    OUT.write_text(md, encoding="utf-8")
    print("wrote", OUT, f"({len(md)} bytes)")


if __name__ == "__main__":
    main()
