#!/usr/bin/env python3
"""Org-wide velocity & health timeline for the sanskrit-lexicon org.

Operates offline on the already-extracted observatory data
(`observatory/site/src/data/timeseries_annual.csv` + `commits.csv`) — no
GitHub calls, fully reproducible. Aggregates the per-repo annual series into
an organization-wide timeline and adds two derived health signals:

* **Active authors** — org-wide DISTINCT commit authors per year (the
  per-repo `unique_authors` column cannot be summed: it double-counts people
  active in several repos, so this is recomputed from `commits.csv`).
* **Issue backlog** — cumulative (opened − closed), i.e. how the open-issue
  debt has grown or been paid down over time.

Outputs
-------
* `reports/velocity_timeline.md`                     — human-readable finding
* `observatory/site/src/data/velocity_timeline.csv`  — per-year org metrics

Usage:  python scripts/velocity_timeline.py
"""
import csv, os, sys
from collections import defaultdict
sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, 'observatory', 'site', 'src', 'data')
ANNUAL = os.path.join(DATA, 'timeseries_annual.csv')
COMMITS = os.path.join(DATA, 'commits.csv')
OUT_MD = os.path.join(ROOT, 'reports', 'velocity_timeline.md')
OUT_CSV = os.path.join(DATA, 'velocity_timeline.csv')

INT_COLS = ['issues_opened', 'issues_closed', 'prs_opened', 'prs_closed', 'commits']


def main():
    agg = defaultdict(lambda: {c: 0 for c in INT_COLS})
    active_repos = defaultdict(set)
    with open(ANNUAL, encoding='utf-8') as f:
        for row in csv.DictReader(f):
            y = row['year']
            vals = {c: int(row[c] or 0) for c in INT_COLS}
            for c in INT_COLS:
                agg[y][c] += vals[c]
            if sum(vals.values()) > 0:
                active_repos[y].add(row['repo'])

    # Org-wide distinct authors per year, recomputed from commits.csv.
    authors = defaultdict(set)
    with open(COMMITS, encoding='utf-8') as f:
        for row in csv.DictReader(f):
            date = row['date']
            if not date:
                continue
            y = date[:4]
            who = (row['author_login'] or '').strip() or (row['author_name'] or '').strip()
            if who:
                authors[y].add(who)

    years = sorted(agg)

    # ---- per-year CSV ----
    cum = 0
    rows_out = []
    for y in years:
        a = agg[y]
        net = a['issues_opened'] - a['issues_closed']
        cum += net
        rows_out.append({
            'year': y,
            'issues_opened': a['issues_opened'],
            'issues_closed': a['issues_closed'],
            'prs_opened': a['prs_opened'],
            'prs_closed': a['prs_closed'],
            'commits': a['commits'],
            'active_repos': len(active_repos[y]),
            'active_authors': len(authors.get(y, set())),
            'net_issues': net,
            'cumulative_open': cum,
        })
    with open(OUT_CSV, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(rows_out[0].keys()))
        w.writeheader()
        w.writerows(rows_out)

    # ---- totals & superlatives ----
    tot = {c: sum(agg[y][c] for y in years) for c in INT_COLS}
    peak_commits = max(rows_out, key=lambda r: r['commits'])
    peak_issues = max(rows_out, key=lambda r: r['issues_opened'])
    peak_repos = max(rows_out, key=lambda r: r['active_repos'])
    peak_authors = max(rows_out, key=lambda r: r['active_authors'])
    first_pr_year = next((r['year'] for r in rows_out if r['prs_opened'] > 0), None)
    peak_backlog = max(rows_out, key=lambda r: r['cumulative_open'])
    last = rows_out[-1]
    pr_recent = last['prs_opened']

    # ---- report ----
    L = []; A = L.append
    A('# Velocity & health timeline')
    A('')
    A(f'_Generated by `scripts/velocity_timeline.py` from '
      f'`observatory/site/src/data/timeseries_annual.csv` and `commits.csv` '
      f'(offline, reproducible). Organization-wide aggregates, '
      f'{years[0]}–{years[-1]}._')
    A('')
    A('## Headline')
    A('')
    A('| Metric | Value |')
    A('|---|---:|')
    A(f'| Commits (all repos, all years) | {tot["commits"]:,} |')
    A(f'| Issues opened / closed | {tot["issues_opened"]:,} / {tot["issues_closed"]:,} |')
    A(f'| Pull requests opened / closed | {tot["prs_opened"]:,} / {tot["prs_closed"]:,} |')
    A(f'| Peak commit year | {peak_commits["year"]} ({peak_commits["commits"]:,}) |')
    A(f'| Peak issue-opening year | {peak_issues["year"]} ({peak_issues["issues_opened"]:,}) |')
    A(f'| Most active repos in a year | {peak_repos["year"]} ({peak_repos["active_repos"]}) |')
    A(f'| Most distinct authors in a year | {peak_authors["year"]} ({peak_authors["active_authors"]}) |')
    A(f'| First year with pull requests | {first_pr_year or "—"} |')
    A('')
    A('## Org-wide timeline')
    A('')
    A('| Year | Commits | Issues + | Issues − | PRs + | Active repos | Active authors | Open-issue backlog |')
    A('|---|---:|---:|---:|---:|---:|---:|---:|')
    for r in rows_out:
        A(f'| {r["year"]} | {r["commits"]:,} | {r["issues_opened"]:,} | '
          f'{r["issues_closed"]:,} | {r["prs_opened"]:,} | {r["active_repos"]} | '
          f'{r["active_authors"]} | {r["cumulative_open"]:,} |')
    A('')
    A('## Reading')
    A('')
    A(f'- **Throughput is real but narrow-shouldered.** {tot["commits"]:,} '
      f'commits and {tot["issues_opened"]:,} issues over {len(years)} years, '
      f'yet the busiest year drew only **{peak_authors["active_authors"]} '
      f'distinct authors** ({peak_authors["year"]}). The activity curve is '
      'driven by volume per person, not by a growing contributor base — the '
      'same concentration the bus-factor finding quantifies '
      '(`reports/bus_factor.md`).')
    A(f'- **Pull requests barely register.** Only {tot["prs_opened"]} PRs in '
      f'{len(years)} years. They first appear in **{first_pr_year}** and stay '
      f'in single digits annually until **{last["year"]}**, when '
      f'{pr_recent} of the {tot["prs_opened"]} lifetime PRs '
      f'({100*pr_recent//tot["prs_opened"]}%) landed. The org runs on direct '
      'commits and issues; review-based contribution is only now emerging.')
    A(f'- **A correction-campaign signature, not steady-state maintenance.** '
      f'The open-issue backlog climbed to a peak of '
      f'{peak_backlog["cumulative_open"]:,} in {peak_backlog["year"]} — after a '
      f'record {peak_issues["issues_opened"]:,} issues were opened org-wide '
      f'that year, driven by `csl-orig`\'s git-based correction workflow — then '
      f'fell sharply to {last["cumulative_open"]:,} in {last["year"]} as '
      f'{last["issues_closed"]:,} issues were closed. Activity comes in '
      'correction waves, not a flat hum.')
    A('')
    A('*Object of analysis: GitHub commits, issues, PRs, and contributors over '
      'time — in scope per `docs/BOUNDARY_RULES.md`.*')

    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')

    print(f'wrote {OUT_MD}')
    print(f'wrote {OUT_CSV}')
    print(f'  years: {years[0]}-{years[-1]}   commits: {tot["commits"]:,}   '
          f'issues: {tot["issues_opened"]:,}/{tot["issues_closed"]:,}   '
          f'PRs: {tot["prs_opened"]:,}')
    print(f'  peak commits: {peak_commits["year"]} ({peak_commits["commits"]:,})   '
          f'peak authors: {peak_authors["year"]} ({peak_authors["active_authors"]})   '
          f'first PR year: {first_pr_year}')


if __name__ == '__main__':
    main()
