#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_consumed_by.py — per-canonical-asset consumed-by view (H1392 Lane-1 step 1.6).

Reads kosha datasets.json (the machine registry of record) + Uprava's interlinks_edges.tsv
(the canonical edge store) and emits one row per canonical asset: owner, tier, live consumers
(names), consumer count, and a zero-consumer flag. The zero-consumer list is the Wave-3
consumption-measurement input (VERIFICATION §2.1). Every datasets.json asset appears exactly once.

Runs where both repos are checked out (locally, or CI with the org-read PAT). The committed
OUTPUT (reports/consumed_by_baseline_2026-07.md) is the artifact of record.

Usage:
  python tools/gen_consumed_by.py [--datasets PATH] [--edges PATH] [--out PATH]
    --datasets : kosha data/manifest/datasets.json (default: ../kosha/data/manifest/datasets.json)
    --edges    : Uprava interlinks_edges.tsv       (default: ../Uprava/interlinks_edges.tsv)
"""
import argparse
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_datasets(p):
    d = json.load(open(p, encoding="utf-8"))
    return d["datasets"] if isinstance(d, dict) and "datasets" in d else (d if isinstance(d, list) else list(d.values()))


def load_edges(p):
    rows = []
    for ln in open(p, encoding="utf-8"):
        if ln.startswith("#") or not ln.strip():
            continue
        c = ln.rstrip("\n").split("\t")
        if c[0] == "source" or len(c) != 7:
            continue
        rows.append(dict(source=c[0], target=c[1], asset=c[2], kind=c[3], status=c[4]))
    return rows


def short(url):
    return (url or "?").rstrip("/").split("/")[-1]


def build(datasets, edges):
    lines, zero = [], []
    lines.append("| Asset | Owner | Tier | Live consumers | Count |")
    lines.append("|---|---|---|---|---|")
    for ds in sorted(datasets, key=lambda x: x.get("id", "")):
        did, title = ds.get("id", "?"), ds.get("title", "")
        owner = short(ds.get("source_repo"))
        tier = ds.get("tier", "?")
        cons = set(ds.get("consumers") or [])
        # augment from edges: live consumes-edges whose asset name overlaps this dataset
        for e in edges:
            if e["status"] != "live":
                continue
            if e["kind"] == "consumes" and (did.lower() in e["asset"].lower() or title.lower()[:20] in e["asset"].lower()):
                cons.add(e["source"])
        conl = sorted(c for c in cons if c)
        row = f"| `{did}` — {title} | {owner} | {tier} | {', '.join(conl) if conl else '—'} | {len(conl)} |"
        lines.append(row)
        if not conl:
            zero.append(f"- `{did}` — {title} ({owner}, {tier})")
    body = "\n".join(lines)
    zsec = "\n".join(zero) if zero else "_none — every manifest asset has ≥1 recorded consumer._"
    return body, zsec, len(datasets), len(zero)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--datasets", default=os.path.abspath(os.path.join(ROOT, "..", "kosha", "data", "manifest", "datasets.json")))
    ap.add_argument("--edges", default=os.path.abspath(os.path.join(ROOT, "..", "Uprava", "interlinks_edges.tsv")))
    ap.add_argument("--out", default=os.path.join(ROOT, "reports", "consumed_by_baseline_2026-07.md"))
    a = ap.parse_args()
    if not os.path.exists(a.datasets):
        print(f"PARKED: datasets.json not found at {a.datasets}")
        return 2
    if not os.path.exists(a.edges):
        print(f"PARKED: edges TSV not found at {a.edges}")
        return 2
    datasets, edges = load_datasets(a.datasets), load_edges(a.edges)
    body, zsec, n, nz = build(datasets, edges)
    out = f"""# Consumed-by baseline — canonical assets and their live consumers (2026-07)

_Created: 20-07-2026 · Last updated: 20-07-2026_

_Auto-generated by [tools/gen_consumed_by.py](https://github.com/sanskrit-lexicon/csl-observatory/blob/main/tools/gen_consumed_by.py) \
from [kosha datasets.json](https://github.com/gasyoun/kosha/blob/main/data/manifest/datasets.json) + \
[Uprava interlinks_edges.tsv](https://github.com/gasyoun/Uprava/blob/main/interlinks_edges.tsv). \
Model: Opus 4.8 (`claude-opus-4-8[1m]`), H1392 Lane-1 step 1.6._

**{n} manifest assets · {nz} with zero recorded consumers.** The zero-consumer list is the
Wave-3 consumption-measurement input (VERIFICATION §2.1): visibility is the point, 0 is allowed.

## Per-asset consumers

{body}

## Zero-consumer assets (Wave-3 input)

{zsec}
"""
    open(a.out, "w", encoding="utf-8", newline="\n").write(out)
    print(f"wrote {os.path.relpath(a.out, ROOT)} — {n} assets, {nz} zero-consumer")
    return 0


if __name__ == "__main__":
    sys.exit(main())
